project:
  type: book

book:
  title: "Estratégia Financeira (Questions)"
  author: "Henrique C. Martins"
  date: last-modified
#  downloads: [pdf]
  chapters:
    - index.qmd
    - part1.qmd
#    - part2.qmd
#    - part3.qmd
#    - part4.qmd
#    - part5.qmd
#    - part6.qmd
#    - part7.qmd
#    - part8.qmd
#    - part9.qmd
#   - part10.qmd
  page-navigation: false
  navbar: false
  sidebar: 
    search: false
    title: false
    style: floating

format:
  html:
    theme: default
    toc: false
#  pdf: default

editor: visual

website:
  comments:
    giscus:
      repo: henriquecastror/comments