project:
  type: website
website:
  title: Henrique Castro Martins
  open-graph: true
  site-url: https://henriquemartins.net/
  google-analytics: G-771J5563G0
  navbar:
    right:
    - href: about.qmd
    - text: Teaching
      href: teaching/
    - text: Research
      href: research/
    - text: Seminars
      href: seminars/
    - text: CV
      href: cv/cv_Henrique_Castro_Martins.pdf
    - icon: linkedin
      href: https://www.linkedin.com/in/henriquecastror/
  page-footer:
    left: Made using [Quarto](https://quarto.org/). Please, cite the website if you
      use the content.
  twitter-card: true
freeze: false
format:
  html:
    theme: litera
    css: include/webex.css
    include-after-body: include/webex.js
    canonical-url: https://henriquemartins.net/
html:
  css: webex.css
  include-after-body: webex.js
editor: visual
