project:
  type: website

website:
  title: "Henrique Castro Martins"
#  reader-mode: true
  -oogle-analytics: "UA-172470817-1"
  navbar:
    right:
      - href: about.qmd
      - text: blog
        href: blog/
      - text: Research
        href: research/
      - text: Teaching
        href: teaching/
      - text: Seminars
        href: seminars/
      - text: CV
        href: cv/cv_Henrique_Castro_Martins.pdf
      - icon: github
        href: https://github.com/henriquecastror
      - icon: linkedin
        href: https://www.linkedin.com/in/henriquecastror/
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by [Henrique C. Martins](mailto:henrique.martins@fgv.br). Feel free to use all content, but please cite the website if you use it. All errors are my own."    
  twitter-card: 
    creator: "@henriquecastror"

format:
  html:
   theme:
    light: litera
    dark: darkly
#    css: styles.css
    toc: true

editor: visual

comments:
  giscus:
    repo: henriquecastror/comments

