project:
  type: website

website:
  title: "Henrique Castro Martins"
#  reader-mode: true
  site-url: "https://henriquemartins.net/"
  google-analytics: "G-771J5563G0"
  navbar:
    right:
      - href: about.qmd
      - text: Teaching
        href: teaching/
      - text: Research
        href: research/
      - text: Seminars
        href: seminars/
 #     - text: Blog
 #       href: blog/
      - text: ABS List
        href: https://hcm.quarto.pub/abs_list/
      - text: CV
        href: cv/cv_Henrique_Castro_Martins.pdf
      - icon: github
        href: https://github.com/henriquecastror
      - icon: linkedin
        href: https://www.linkedin.com/in/henriquecastror/
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by [Henrique C. Martins](mailto:henrique.martins@fgv.br). Please, cite the website if you use the content."    
  twitter-card: true

freeze: false  

format:
  html:
   theme:
    light: litera
    dark: darkly
#    css: styles.css
#    toc: true

editor: visual

#comments:
#  giscus:
#    repo: henriquecastror/comments

