{
  "hash": "ad19b40500227ccad95d4d3dfc2b360a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Empirical Methods in Finance'\nsubtitle: 'Practicing 1'\nauthor: 'Henrique C. Martins'\nformat:\n  revealjs: \n    slide-number: true\n    theme: simple\n    chalkboard: true\n    preview-links: auto\n    logo: figs/background8.png\n    css: logo.css\n    footer: '**[**Henrique C. Martins**] [[henrique.martins@fgv.br](mailto:henrique.martins@fgv.br)][Do not use without permission]**  '\n    multiplex: true\n    scrollable: true \ntitle-slide-attributes:\n    data-background-color: \"#b1cafa\"\ninclude-after: |\n  <script type=\"text/javascript\">\n    Reveal.on('ready', event => {\n      if (event.indexh === 0) {\n        document.querySelector(\"div.has-logo > img.slide-logo\").style.display = \"none\";\n      }\n    });\n    Reveal.addEventListener('slidechanged', (event) => {\n      if (event.indexh === 0) {\n        Reveal.configure({ slideNumber: null });\n        document.querySelector(\"div.has-logo > img.slide-logo\").style.display = \"none\";\n      }\n      if (event.indexh === 1) { \n        Reveal.configure({ slideNumber: 'c' });\n        document.querySelector(\"div.has-logo > img.slide-logo\").style.display = null;\n      }\n    });\n  </script>\n\n---\n\n\n\n\n\n\n\n\n\n\n\n# Basic Statistics {.smaller}\n\n## Basic stats {.smaller }\n\nThe following are simple examples of how to compute basic statistics using R. We will start importing the data. Let's use the free dataset `iris`, available in R.\n\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\niris <- iris \n```\n:::\n\n\n\nFirst, explore the dataset.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nstr(iris) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t150 obs. of  5 variables:\n $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...\n $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...\n $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...\n $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...\n $ Species     : Factor w/ 3 levels \"setosa\",\"versicolor\",..: 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\n\n- We have 5 variables: Sepal.Length, Sepal.Width, Petal.Length, Petal.Width e Species. The first four are numeric while the last is a string with three groups: setosa, versicolor, and virginica. The dataset contains 150 observations\n\n\n\n\n\n\n\n## Basic stats {.smaller }\n\nLet's take a look at the first 10 observations in the dataset.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nhead(iris, 10) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1           5.1         3.5          1.4         0.2  setosa\n2           4.9         3.0          1.4         0.2  setosa\n3           4.7         3.2          1.3         0.2  setosa\n4           4.6         3.1          1.5         0.2  setosa\n5           5.0         3.6          1.4         0.2  setosa\n6           5.4         3.9          1.7         0.4  setosa\n7           4.6         3.4          1.4         0.3  setosa\n8           5.0         3.4          1.5         0.2  setosa\n9           4.4         2.9          1.4         0.2  setosa\n10          4.9         3.1          1.5         0.1  setosa\n```\n\n\n:::\n:::\n\n\n\n## Basic stats {.smaller }\n\n\nNow, let's take a look at the first 5 observations of each species.\n\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nby(iris,iris[\"Species\"],head,n=5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpecies: setosa\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1          5.1         3.5          1.4         0.2  setosa\n2          4.9         3.0          1.4         0.2  setosa\n3          4.7         3.2          1.3         0.2  setosa\n4          4.6         3.1          1.5         0.2  setosa\n5          5.0         3.6          1.4         0.2  setosa\n------------------------------------------------------------ \nSpecies: versicolor\n   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species\n51          7.0         3.2          4.7         1.4 versicolor\n52          6.4         3.2          4.5         1.5 versicolor\n53          6.9         3.1          4.9         1.5 versicolor\n54          5.5         2.3          4.0         1.3 versicolor\n55          6.5         2.8          4.6         1.5 versicolor\n------------------------------------------------------------ \nSpecies: virginica\n    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species\n101          6.3         3.3          6.0         2.5 virginica\n102          5.8         2.7          5.1         1.9 virginica\n103          7.1         3.0          5.9         2.1 virginica\n104          6.3         2.9          5.6         1.8 virginica\n105          6.5         3.0          5.8         2.2 virginica\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Mean and Median {.smaller }\n\nNow, let's find the means and the medians of the four numeric variables. The most intuitive way is as follows.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmean(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.843333\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmean(iris$Sepal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.057333\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmean(iris$Petal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.758\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmean(iris$Petal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.199333\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmedian(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.8\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmedian(iris$Sepal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmedian(iris$Petal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.35\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmedian(iris$Petal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.3\n```\n\n\n:::\n:::\n\n\n\n\n## Mean and Median {.smaller }\n\nBut this is the easiest way.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nsummary(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   \n Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  \n 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  \n Median :5.800   Median :3.000   Median :4.350   Median :1.300  \n Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  \n 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  \n Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  \n       Species  \n setosa    :50  \n versicolor:50  \n virginica :50  \n                \n                \n                \n```\n\n\n:::\n:::\n\n\n\n\n## Mean and Median {.smaller }\n\nSee that in the code above you also have the number of observations of each species. If you wanted to know how many observations you have in the dataset, you could use the following line. This might be important in the future.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nlength(iris$Species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150\n```\n\n\n:::\n:::\n\n\n\n## Mean and Median {.smaller }\n\nIf you want the same thing by group, do as follows:\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nby(iris, iris$Species, summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\niris$Species: setosa\n  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   \n Min.   :4.300   Min.   :2.300   Min.   :1.000   Min.   :0.100  \n 1st Qu.:4.800   1st Qu.:3.200   1st Qu.:1.400   1st Qu.:0.200  \n Median :5.000   Median :3.400   Median :1.500   Median :0.200  \n Mean   :5.006   Mean   :3.428   Mean   :1.462   Mean   :0.246  \n 3rd Qu.:5.200   3rd Qu.:3.675   3rd Qu.:1.575   3rd Qu.:0.300  \n Max.   :5.800   Max.   :4.400   Max.   :1.900   Max.   :0.600  \n       Species  \n setosa    :50  \n versicolor: 0  \n virginica : 0  \n                \n                \n                \n------------------------------------------------------------ \niris$Species: versicolor\n  Sepal.Length    Sepal.Width     Petal.Length   Petal.Width          Species  \n Min.   :4.900   Min.   :2.000   Min.   :3.00   Min.   :1.000   setosa    : 0  \n 1st Qu.:5.600   1st Qu.:2.525   1st Qu.:4.00   1st Qu.:1.200   versicolor:50  \n Median :5.900   Median :2.800   Median :4.35   Median :1.300   virginica : 0  \n Mean   :5.936   Mean   :2.770   Mean   :4.26   Mean   :1.326                  \n 3rd Qu.:6.300   3rd Qu.:3.000   3rd Qu.:4.60   3rd Qu.:1.500                  \n Max.   :7.000   Max.   :3.400   Max.   :5.10   Max.   :1.800                  \n------------------------------------------------------------ \niris$Species: virginica\n  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   \n Min.   :4.900   Min.   :2.200   Min.   :4.500   Min.   :1.400  \n 1st Qu.:6.225   1st Qu.:2.800   1st Qu.:5.100   1st Qu.:1.800  \n Median :6.500   Median :3.000   Median :5.550   Median :2.000  \n Mean   :6.588   Mean   :2.974   Mean   :5.552   Mean   :2.026  \n 3rd Qu.:6.900   3rd Qu.:3.175   3rd Qu.:5.875   3rd Qu.:2.300  \n Max.   :7.900   Max.   :3.800   Max.   :6.900   Max.   :2.500  \n       Species  \n setosa    : 0  \n versicolor: 0  \n virginica :50  \n                \n                \n                \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Minimum and maximum  {.smaller }\n\nThe function `summary`already gives you the minimum and maximum of all variables. But sometimes you need to find only these values. You could use the following lines.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmin(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.3\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmax(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.9\n```\n\n\n:::\n:::\n\n      \nYou could also find the range of values to find the extreme values of a variable.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nrange(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.3 7.9\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Minimum and maximum  {.smaller }\n\nIf you need the distance between the extreme values, you can use:\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\nmax(iris$Sepal.Length) - min(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.6\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Standard-deviation and Variance {.smaller }\n\nFinally, you can also compute the Standard-deviation and Variance of one variable as follows.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nsd(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8280661\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nvar(iris$Sepal.Length) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6856935\n```\n\n\n:::\n:::\n\n\nIf you want the standard deviation of all variables:\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nlapply(iris[, 1:4], sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Sepal.Length\n[1] 0.8280661\n\n$Sepal.Width\n[1] 0.4358663\n\n$Petal.Length\n[1] 1.765298\n\n$Petal.Width\n[1] 0.7622377\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n \n## Correlation {.smaller }\n\nThe following lines will show you a correlation table. First, you need to create a new dataframe with only the numeric variables. This is an extremely important table to your academic paper.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nlibrary(dplyr)\niris_num <- select(iris,-Species)\ncor(iris_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Sepal.Length Sepal.Width Petal.Length Petal.Width\nSepal.Length    1.0000000  -0.1175698    0.8717538   0.8179411\nSepal.Width    -0.1175698   1.0000000   -0.4284401  -0.3661259\nPetal.Length    0.8717538  -0.4284401    1.0000000   0.9628654\nPetal.Width     0.8179411  -0.3661259    0.9628654   1.0000000\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Frequence table {.smaller }\n\nHere is another important table you might use in your paper: the frequency of observations by group.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\ntable(iris$Species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    setosa versicolor  virginica \n        50         50         50 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n## T-test {.smaller }\n\nLet's create now a t-test of the difference in means. For that, we will use another dataset: `mtcars`. The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles. You can find the description of the variables [here](https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/mtcars).\n\nYou will find that there is one variable that is binary: either the cars are automatic (1) or are manual (0).\n\nWhen you have binary variables, it is always a good idea to test if the means of the variables are different between the two groups of the binary variable.\n\nThis is a big thing and you will use a lot in your academic research. In fact, in many articles, the authors explore and compare two groups. So, be ready to create such an analysis.  \n\n\n\n\n\n\n\n## T-test {.smaller }\n\nFirst, import the new dataset. Then, repeat the first steps and inspect this dataset (I will not inspect the dataset here, but you should inspect as a way to practice it). \n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nmtcars <- mtcars\n```\n:::\n\n\n\n\n## T-test {.smaller }\n\nThen, use the binary variable to see if other variables have similar means. The following case compares the average of `mpg` (miles p/ gas) of automatic vs. manual car.\n\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"false\" code-summary=\"R\" code-line-numbers=\"true\"}\nt.test(mpg ~ am, data=mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  mpg by am\nt = -3.7671, df = 18.332, p-value = 0.001374\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -11.280194  -3.209684\nsample estimates:\nmean in group 0 mean in group 1 \n       17.14737        24.39231 \n```\n\n\n:::\n:::\n\n\n- We see that the average in the automatic car is around 17.1 while the average of manual cars is 24.3.\n- These averages are statistically different, since the t-stat is high (-3.76).\n- So, we can learn that automatic cars consume more gas than manual cars.\n- This type of test will be very  important in your research.\n\n\n\n\n\n\n\n## Dispersion {.smaller}\n\nThese measures show how *spread out* the data are around the mean.  \n\nThe coefficient of variation (CV) compares variability relative to the mean — useful in finance for comparing volatility across assets.\n\nInterquartile Range = $Q_3 - Q_1$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nx <- iris$Sepal.Length\nrange_x <- range(x)\niqr_x   <- IQR(x)\ncv_x    <- sd(x) / mean(x)\n\nlist(\n  range = diff(range_x),\n  IQR = iqr_x,\n  CV = cv_x\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$range\n[1] 3.6\n\n$IQR\n[1] 1.3\n\n$CV\n[1] 0.1417113\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Quantiles & Percentiles {.smaller}\n\nQuantiles divide the data into equal parts (e.g., quartiles, percentiles).\n\nThey are often used to identify thresholds or outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nquantile(iris$Sepal.Length, probs = c(.01,.05,.25,.50,.75,.95,.99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   1%    5%   25%   50%   75%   95%   99% \n4.400 4.600 5.100 5.800 6.400 7.255 7.700 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Distributions {.smaller}\n\nVisualizing the distribution helps you see its shape — whether symmetric, skewed, or concentrated.\n\nEmpirical Cumulative Distribution Function (ECDF) = y-axis shows the accumulated proportion of observations below the x-value.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\npar(mfrow = c(1,3))\nhist(iris$Sepal.Length, breaks = 10, main = \"Histogram\", xlab = \"Sepal.Length\")\nplot(density(iris$Sepal.Length), main = \"Kernel Density\", xlab = \"Sepal.Length\")\nplot(ecdf(iris$Sepal.Length), main = \"ECDF\", xlab = \"Sepal.Length\")\n```\n\n::: {.cell-output-display}\n![](part_O1_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=960}\n:::\n\n```{.r .cell-code  code-line-numbers=\"true\"}\npar(mfrow = c(1,1))\n```\n:::\n\n\n\n\n\n\n## Shape: Skewness & Kurtosis {.smaller}\n\nThese measures describe the *shape* of a distribution.  \n- **Skewness:** measures symmetry (right- or left-tailed).  \n- **Kurtosis:** measures tail heaviness (fat tails → more extreme events).  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nset.seed(123)\nx_sym  <- rnorm(1000, mean = 0, sd = 1)        # symmetric (normal)\nx_right <- rexp(1000, rate = 1) - 1            # right-skewed\nx_fat  <- rt(1000, df = 3)                     # heavy tails (t-distribution)\n\npar(mfrow = c(1,3))\nhist(x_sym, breaks = 25, main = \"Symmetric (Normal)\", col = \"lightgray\", xlab = \"\")\nhist(x_right, breaks = 25, main = \"Right-Skewed (Exponential)\", col = \"lightgray\", xlab = \"\")\nhist(x_fat, breaks = 25, main = \"Fat Tails (t, df=3)\", col = \"lightgray\", xlab = \"\")\n```\n\n::: {.cell-output-display}\n![](part_O1_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=960}\n:::\n\n```{.r .cell-code  code-line-numbers=\"true\"}\npar(mfrow = c(1,1))\n```\n:::\n\n\n\n## Shape: Skewness & Kurtosis {.smaller}\n\nNow, let's compute skewness and kurtosis for our actual data.\n\n\n- Skewness > 0 → right tail longer (positive skew).\n- Skewness < 0 → left tail longer (negative skew).\n- Kurtosis > 0 → heavier tails than normal (leptokurtic).\n- Kurtosis < 0 → lighter tails than normal (platykurtic).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nskewness <- function(v){\n  m <- mean(v); s <- sd(v)\n  mean(((v - m)/s)^3)\n}\nkurtosis_excess <- function(v){\n  m <- mean(v); s <- sd(v)\n  mean(((v - m)/s)^4) - 3\n}\nc(\n  skewness = skewness(iris$Sepal.Length),\n  excess_kurtosis = kurtosis_excess(iris$Sepal.Length)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       skewness excess_kurtosis \n      0.3086407      -0.6058125 \n```\n\n\n:::\n:::\n\n\n\n\n## Outliers via IQR Rule {.smaller}\n\nOutliers are points far from most observations. The IQR rule defines them as values beyond 1.5 × IQR from the quartiles.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nx <- iris$Sepal.Length\nQ1 <- quantile(x, .25); Q3 <- quantile(x, .75); I <- IQR(x)\nlower <- Q1 - 1.5*I; upper <- Q3 + 1.5*I\nout_idx <- which(x < lower | x > upper)\nlist(\n  thresholds = c(lower = lower, upper = upper),\n  n_outliers = length(out_idx),\n  example_values  = head(x[out_idx], 5)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$thresholds\nlower.25% upper.75% \n     3.15      8.35 \n\n$n_outliers\n[1] 0\n\n$example_values\nnumeric(0)\n```\n\n\n:::\n:::\n\n\n\n\n\n## Transformations: log & z-score {.smaller}\n\nTransformations help stabilize variance and make variables comparable.\n\n- log(x) reduces skewness.\n- z-score standardizes scale.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nx     <- iris$Sepal.Length\nx_log <- log(x)\nx_z   <- as.numeric(scale(x))\npar(mfrow = c(1,3))\nhist(x, main=\"Original\", xlab=\"Sepal.Length\")\nhist(x_log, main=\"log(x)\", xlab=\"log(Sepal.Length)\")\nhist(x_z, main=\"z-score\", xlab=\"Standardized\")\n```\n\n::: {.cell-output-display}\n![](part_O1_files/figure-revealjs/unnamed-chunk-24-1.png){fig-align='center' width=960}\n:::\n\n```{.r .cell-code  code-line-numbers=\"true\"}\npar(mfrow = c(1,1))\n```\n:::\n\n\n\n\n\n\n\n\n\n# Confidence Intervals {.smaller}\n\n## What is a Confidence Interval? {.smaller}\n\nA confidence interval reflects the *uncertainty* around an estimate.  \nIf we repeat the experiment many times, most intervals will capture the true mean, but some will miss it just by chance.\n\nBelow, we simulate **100 random samples** (each with 30 observations from a true mean of 5).  \nEach horizontal line shows a 95% confidence interval for one sample mean.  \nThe **red line** marks the *true mean (μ = 5)*.  \n\n- Gray dots: sample means  \n- Gray bars: confidence intervals  \n- Intervals that **miss** the red line show random sampling error  \n- About **5 out of 100** intervals are expected to miss (≈5%)\n\n👉 A 95% CI means: *if we repeated the experiment many times, 95% of the intervals would contain the true mean.*\n\n\n\n\n\n## Visual Intuition {.smaller}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nset.seed(123)\nn <- 30\nNrep <- 100\nmu <- 5; sigma <- 1\nsamples <- replicate(Nrep, rnorm(n, mu, sigma))\nmeans <- colMeans(samples)\nses <- apply(samples, 2, sd) / sqrt(n)\nlower <- means - qt(0.975, df = n-1) * ses\nupper <- means + qt(0.975, df = n-1) * ses\n\nplot(1:Nrep, means, ylim = c(4,6), pch = 19, col = \"gray40\",\n     ylab = \"Mean estimate\", xlab = \"Sample\",\n     main = \"100 simulated 95% Confidence Intervals\")\nsegments(1:Nrep, lower, 1:Nrep, upper, col = \"gray60\")\nabline(h = mu, col = \"red\", lwd = 2)\nlegend(\"topright\", legend=\"True mean\", col=\"red\", lwd=2, bty=\"n\")\n```\n\n::: {.cell-output-display}\n![](part_O1_files/figure-revealjs/unnamed-chunk-25-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n## Confidence Interval for Iris Data {.smaller}\n\nCompute a real example for Sepal.Length.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nt.test(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  iris$Sepal.Length\nt = 86.425, df = 149, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 5.709732 5.976934\nsample estimates:\nmean of x \n 5.843333 \n```\n\n\n:::\n:::\n\n\n👉 The output shows:\n\n- Sample mean\n- Confidence limits\n- t-statistic and p-value\n\nYou can visualize the result below.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nx <- iris$Sepal.Length\nm <- mean(x)\nse <- sd(x)/sqrt(length(x))\nci <- m + c(-1,1)*qt(0.975, df=length(x)-1)*se\n\nhist(x, breaks = 15, col = \"lightgray\",\n     main = \"95% Confidence Interval for Sepal.Length\",\n     xlab = \"Sepal.Length\")\nabline(v = m, col = \"blue\", lwd = 2)\nabline(v = ci, col = \"red\", lty = 2, lwd = 2)\nlegend(\"topright\", legend=c(\"Mean\", \"95% CI limits\"), \n       col=c(\"blue\",\"red\"), lwd=2, lty=c(1,2), bty=\"n\")\n```\n\n::: {.cell-output-display}\n![](part_O1_files/figure-revealjs/unnamed-chunk-27-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n## 🙋️ **Any Questions?**{ .smaller  background=\"#fdf6e3\"}\n\n::: columns\n::: {.column width=\"50%\"}\n### Thank You!\n\n![](figs/qa2.png){width=\"110%\" style=\"box-shadow: none;\"}\n\n:::\n\n::: {.column width=\"50%\"}\n<div style=\"text-align:right;\">\n  <img src=\"figs/avatar.jpg\" width=\"120px\" style=\"border-radius:50%; box-shadow:0 4px 12px rgba(0,0,0,.25);\" />\n</div>\n\n### **Henrique C. Martins**\n\n- 🌐 [FGV/EAESP](https://eaesp.fgv.br/en/people/henrique-castro-martins)  \n- 💼 [LinkedIn](https://www.linkedin.com/in/henriquecastror/)  \n- 🧠 [Google Scholar](https://scholar.google.com.br/citations?user=7gIfkRMAAAAJ&hl=pt-BR&oi=ao)  \n- 📄 [Lattes CV](http://lattes.cnpq.br/6076997472159785)  \n- 🏠 [Personal Website](https://henriquemartins.net/)  \n:::\n:::\n\n",
    "supporting": [
      "part_O1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}