---
title: "Financial Strategy - 2025/01"
---

___


::: {.callout-important}
### For students

Below you find the persistent links to all lectures of the course. As they are continuously updated with fixes and new implementations, **you might expect some changes from time to time in the contents of each file**.

These slides leverage [Quarto](https://quarto.org/), an open-source scientific and technical publishing system. They contain both static and dynamic content that will be displayed in your internet browser. 

The Slides and Questions are based or inspired on either [**Berk & DeMarzo, Corporate Finance, 5th ed. 2020**](https://www.amazon.com.br/Corporate-Finance-Global-Jonathan-Berk/dp/1292304154) or 
[**Brealey & Myers, Principles of Corporate Finance, 13th ed. 2020**](https://www.amazon.com.br/Principles-Corporate-Finance-Richard-Brealey/dp/1260565556/ref=sr_1_3?refinements=p_27%3ABrealey+Myers&s=books&sr=1-3).

Additional tips:

1. Hit `F` for full-screen mode
2. If you are interest in getting a `.pdf` version of the slides, hit `E` to switch to print mode and then `Ctrl + P`

:::

___



**Introduction**

-   `Part 0`: [Slides](p0.qmd) 

___

**Part 1 (until Midterm)**

-   `Part 01 (ch23)`: [Slides](p1.qmd) / [Questions T/F & MC](p1tf.qmd) / [Questions Numeric](p1num.qmd) 
-   `Part 02 (ch10)`: [Slides](p2.qmd) / [Questions T/F & MC](p2tf.qmd) / [Questions Numeric](p2num.qmd) 
-   `Part 03 (ch11)`: [Slides](p3.qmd) / [Questions T/F & MC](p3tf.qmd) / [Questions Numeric](p3num.qmd)  
-   `Part 04 (ch12)`: [Slides](p4.qmd) / [Questions T/F & MC](p4tf.qmd) / [Questions Numeric](p4num.qmd)  
-   `Part 05 (ch13)`: [Slides](p5.qmd) / [Questions T/F & MC](p5tf.qmd) / [Questions Numeric](p5num.qmd)  



___

**Part 2 (Midterm to Final)**

-   `Part 06 (ch24)`: [Slides](p6.qmd) / [Questions T/F & MC](p6tf.qmd) 
-   `Part 07 (ch14)`: [Slides](p7.qmd) / [Questions T/F & MC](p7tf.qmd) 
-   `Part 08 (ch15)`: [Slides](p8.qmd) / [Questions T/F & MC](p8tf.qmd) 
-   `Part 09 (ch16)`: [Slides](p9.qmd) / [Questions T/F & MC](p9tf.qmd) 
-   `Part 10 (ch17)`: [Slides](p10.qmd) / [Questions T/F & MC](p10tf.qmd) 

___



