---
title: "Part 3 (ch11) Questions Numeric"
---

::: {style="display: flex; justify-content: space-between; width: 100%;"}
[Go to previous chapter](p2num.qmd){.btn .btn-primary role="button" data-toggle="tool" style="margin-right: 430px;"}
[Go to next chapter](p4num.qmd){.btn .btn-primary role="button" data-toggle="tool"}
:::


::: {.callout-note}
### For students

**Last updated: `r format(Sys.time(), '%d/%m/%Y')`  **

**Type your answers with "." instead of ","! For numerical answers, use 2 decimal places. For instance, if your answer is 0.12345 or 12.345%, type, "12.34" in the box.**

:::



## Question 1


```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
library(webexercises)
w1 <- rnorm(1, mean = 0.40, sd = 0.1)
w2 <- 1 - w1

r1 <- rnorm(1, mean = 0.08, sd = 0.1)
r2 <- rnorm(1, mean = 0.06, sd = 0.1)

sigma1 <- rnorm(1, mean = 0.25, sd = 0.03)
sigma2 <- rnorm(1, mean = 0.15, sd = 0.02)

correl <- rnorm(1, mean = 0.5, sd = 0.2)

```

**Q:** What is the **expected return** of a portfolio that invests `r round(w1,3)` percent in Asset 1 (expected return = `r round(r1,3)`)  and the remaining `r round(w2,3)` in Asset 2 (expected return = `r round(r2,3)`)? 

`r fitb( round( (w1 * r1 + w2 * r2) * 100 ,3) , tol=0.01)`


**Q:** Assuming that the correlation between these assets is `r round(correl,3)`, and that the standard deviation of Asset 1 is `r round(sigma1,3)` while the standard deviation of Asset 2 is `r round(sigma2,3)`, what is the **variance** of the portfolio above?

`r fitb( round( (w1^2 * sigma1^2 + w2^2 * sigma2^2 + 2 * w1 * w2 * correl * sigma1 * sigma2)* 100  ,3) , tol=0.01)`



**Q:** Assuming that the correlation between these assets is `r round(correl,3)`, and that the standard deviation of Asset 1 is `r round(sigma1,3)` while the standard deviation of Asset 2 is `r round(sigma2,3)`, what is the **standard deviation** of the portfolio above?

`r fitb( round( sqrt(w1^2 * sigma1^2 + w2^2 * sigma2^2 + 2 * w1 * w2 * correl * sigma1 * sigma2 ) * 100,3) , tol=0.01)`


___


**Answer**

1) `r round( (w1 * r1 + w2 * r2) * 100 ,3) `

2) `r round( (w1^2 * sigma1^2 + w2^2 * sigma2^2 + 2 * w1 * w2 * correl * sigma1 * sigma2) * 100  ,3) `

3) `r round( sqrt(w1^2 * sigma1^2 + w2^2 * sigma2^2 + 2 * w1 * w2 * correl * sigma1 * sigma2 )* 100 ,3) `






___


<script src="https://giscus.app/client.js"
        data-repo="henriquecastror/EF_permanent"
        data-repo-id="R_kgDOLMIejg"
        data-category="General"
        data-category-id="DIC_kwDOLMIejs4Cc1yS"
        data-mapping="number"
        data-term="6"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>


::: {style="display: flex; justify-content: space-between; width: 100%;"}
[Go to previous chapter](p2num.qmd){.btn .btn-primary role="button" data-toggle="tool" style="margin-right: 430px;"}
[Go to next chapter](p4num.qmd){.btn .btn-primary role="button" data-toggle="tool"}
:::
