---
title: 'Estratégia Financeira/Financial Strategy'
subtitle: ' **Part 10 - Ch 17 Payout Policy** '
author:
  - name: ' **Henrique C. Martins (henrique.martins@fgv.br)** '
    affiliation: '**[FGV/EAESP](https://eaesp.fgv.br/en) **'
  - name: ' **Rafael B. Palazzi (rafaelpalazzi@gmail.com)** '
    affiliation: '**[FGV/EAESP](https://eaesp.fgv.br/en) **'
date-modified: last-modified
title-block-banner: true
format:
  html:
    css: webex.css
    include-after-body: webex.js
---




```{r, setup}
#| eval: true
#| results: asis
#| echo: false
#| warning: false

library(webexercises)

```


**In-class problems about *chapter 15 Debt and Taxes* by [Berk and Demarzo](https://www.amazon.com.br/Corporate-Finance-Global-Jonathan-Berk/dp/1292304154). **


**Solve these problems in class or soon after.**



::: {.callout-important}
**Type your answers with "." instead of ","!**
:::


## True or False





```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** An open market repurchase allows a company to buy back its own shares directly from shareholders at a specific price."
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** Modigliani-Miller theorem suggests that dividend policy is irrelevant in a world of perfect capital markets, as it doesn't affect the overall value of the firm."
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** According to financial theory, retaining earnings and not paying dividends is always the most value-maximizing approach for a company."
q1_choices <- c( "True", answer="False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** Holding excess cash in a firm can lead to inefficiencies and agency costs, which may be reduced by paying out dividends or engaging in share repurchases."
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** In the presence of asymmetric information between managers and investors, payout decisions may serve as signals of the firm's future prospects. Managers with better information may strategically set a firm's payout to communicate their private knowledge to the market."
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** According to the dividend signaling hypothesis, when a company increases its dividend payments, it generally signals that it expects lower future earnings."
q1_choices <- c( "True", answer= "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** According to the Modigliani-Miller theorem, dividend policy has a significant impact on a firm's overall value."
q1_choices <- c( "True", answer= "False")
cat(q1,longmcq(q1_choices))
```




::: {.callout-warning}
**Type your answers with "." instead of ","!**
:::
