{
  "hash": "2cb14f0528354be89da6e7b73781b707",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Inferência Causal'\nsubtitle: 'Part 2'\nauthor: 'Henrique C. Martins'\nformat:\n  revealjs: \n    slide-number: true\n    theme: simple\n    chalkboard: true\n    preview-links: auto\n    logo: figs/background2.png\n    css: styles.css\n    footer: <https://eaesp.fgv.br/>\n    multiplex: true\n---\n\n\n\n\n\n\n\n\n# Selection Bias {.smaller background=\"#f7e8dc\"}\n\n## Selection Bias {.smaller background=\"#f7e8dc\"}\n\nBack to the selection bias example of before.\n\n-   Imagine that John and Mary are moving to the north of Canada.\n\n-   John has a history of respiratory disease and decide to buy insurance.\n\n-   Mary does not have a history of respiratory disease and decide not to buy insurance.\n\n\n\n| Default                     | John | Mary |\n|-----------------------------|:-----|-----:|\n| State of insurance          | 1    |    0 |\n| Situation without insurance | `3`  |    5 |\n| Situation with insurance    | 4    |  `5` |\n| Observed                    | 4    |    5 |\n| Effect                      | ?    |    ? |\n\n$$(Y_{1,john} - Y_{0,john}) + (Y_{1,Mary}- Y_{0,Mary}) = 4 - 3 + 5 - 5 = 0.5$$\n\n\n\n## Selection Bias {.smaller background=\"#f7e8dc\"}\n\nRearranging the terms:\n\n\n$$(Y_{1,john} - Y_{0,Mary})   + (Y_{1,Mary}  - Y_{0,john})  = (4 - 5) + (5 - 3)  = 0.5$$\n$$We\\;see   + We\\;do\\;not\\;see  = (4 - 5) + (5 - 3)  = 0.5$$\n\nThe term $(Y_{1,Mary}  - Y_{0,john}) =  (5 - 3) = 2$ is the **selection bias**.\n\nIt exists because we are comparing two people that should not be compared.\n\n\n\n\n## Selection Bias {.smaller background=\"#f7e8dc\"}\n\nSome notation:\n\n$d=1$ for the treated units (treatment group)\n\n$d=0$ for the treated units (control group)\n\n\n. . . \n\n\n$Y_{i}$ = Potential outcome of individual *i*.\n\n$Y_{i,1}$ or  $Y(1)$ = Potential outcome of individual *i*, treatement group.\n\n$Y_{i,0}$ or  $Y(0)$ = Potential outcome of individual *i*, control group.\n\n\n\n\n\n\n\n\n## Selection Bias {.smaller background=\"#f7e8dc\"}\n\nSome notation:\n\nThese are the representations of the **causal effect** we often want to estimate.\n\n**Average Treatment Effect:**\n\nATE = $\\frac{1}{N} (E[Y_{i,1}] - E[Y_{i,0}])$\n\n. . . \n\n**Average Treatment Effect on the treated:**\n\nATET = $\\frac{1}{N} (E[Y_{i,1}|D_i=1] - E[Y_{i,0}|D_i=1])$\n\n. . . \n\n**Average Treatment Effect on the untreated:**\n\nATEU = $\\frac{1}{N} (E[Y_{i,1}|D_i=0] - E[Y_{i,0}|D_i=0])$\n\n. . . \n\nOf course, again, we cannot observe both potential outcomes of the same unit *i*.\n\n\n\n\n\n\n\n## Selection Bias {.smaller background=\"#f7e8dc\"}\n\nWhen dealing with **causal inference**, we have to find ways to approximate what the hidden potential outcome of the treated units is. \n\nThat is, the challenge in identifying causal effects is that the untreated potential outcomes, $Y_{i,0}$, are never\nobserved for the treated group ($D_i= 1$). The \"second\" term in the following equation:\n\nATET = $\\frac{1}{N} (E[Y_{i,1}|D_i=1] - E[Y_{i,0}|D_i=1])$\n\n\nWe need an empirical design to **\"observe\"** what we do not really observe (i.e., the counterfactual). \n\n\n\n\n\n## Selection Bias {.smaller background=\"#f7e8dc\"}\n\nMany options:\n\n- Matching/Balancing\n- Difference-in-differences (DiD)\n- Instrumental variables\n- Regression discontinuity design (RDD)\n- Synthetic control (Synth)\n\n\n\n\n\n\n\n\n## Selection Bias {.smaller background=\"#f7e8dc\"}\n\nThe process of finding units that are comparable is called **matching**.\n\n. . .\n\n**Before we continue...**\n\n**We will match on observables. We cannot be on unobservables.**\n\nThus, you may want to write in your article \"selection bias due to observables\".\n\n. . .\n\n**Cunningham:**\n\n*Propensity score matching has not seen as wide adoption among economists as in other nonexperimental methods like regression discontinuity or difference-in-differences. The most common reason given for this is that economists are oftentimes skeptical that CIA can be achieved in any dataset almost as an article of faith. This is because for many applications, economists as a group are usually more concerned about selection on unobservables than they are selection on observables, and as such, they reach for matching methods less often.*\n\nCIA = CMI\n\n\n\n\n\n\n\n\n# Matching  {.smaller background=\"#f2d5bf\"}\n\n## Matching   {.smaller background=\"#f2d5bf\"}\n\n**Matching** aims to compare the outcomes between observations that have the same values of all control variables, except that one unit is treated and the other is not. \n\n. . .\n\nIn this literature, the control variables used to matched are often called **covariates**.\n\nThat is, for each treated unit, the researcher finds an untreated unit that is similar in all covariates.\n\nThe implication is that the researcher can argue that \"*units are comparable after matching*\". \n\n\n\n\n\n\n\n## Matching   {.smaller background=\"#f2d5bf\"}\n\nThe easiest to see is **exact matching**: *it matches observations that have the exact same values*. \n\n- It might be doable if you have only one covariate. \n\n- Naturally, if you have only one covariate, you might still be left with some selection bias.\n\n  - In the previous example, health history is one important covariate that makes John and Mary different. \n  \n  - But what about life style? Nutrition? Etc. \n  \n\nAs the number of covariates grow, you cannot pursue exact matching. That is the job of PSM.\n\n\n\n\n\n\n\n## Matching   {.smaller background=\"#f2d5bf\"}\n\n**In exact matching, the causal effect estimator (ATET) is:**\n\n$$ATET = \\frac{1}{N} \\sum (E[Y_{i}] - E[Y_{j(i)}] | D_i=1)$$\n\nWhere $Y_{j(i)}$ is the j-th unit matched to the i-th unit based on the j-th being “closest to” the i-th unit for some  covariate. \n\nFor instance, let’s say that a unit in the treatment group has a covariate with a value of 2 and we find another unit in the control group (exactly one unit) with a covariate value of 2. \n\nThen we will impute the treatment unit’s missing counterfactual with the matched unit’s, and take a difference.\n\n\n\n\n\n\n\n## Matching {.smaller background=\"#f2d5bf\"}\n\nConsider the following dataset from Cunningham:\n\n![](figs/scott.png)\n\n\n\n\n\n## Matching   {.smaller background=\"#f2d5bf\"}\n\n::: panel-tabset\n### R Averages\n\nAverage ages are very different. The salary of a 24 yrs old person is quite different than the salary of a 32 yrs person.\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# Load necessary packages\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(knitr)\nlibrary(kableExtra)\n\nread_data <- function(df)\n{\n  full_path <- paste(\"https://github.com/scunning1975/mixtape/raw/master/\",df, sep = \"\")\n  df <- read_dta(full_path)\n  return(df)\n}\ntraining_example <- read_data(\"training_example.dta\") %>% slice(1:20)\nsummary(training_example$age_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  18.00   20.25   23.00   24.30   28.50   33.00      10 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\nsummary(training_example$age_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  18.00   23.50   31.50   31.95   39.00   51.00 \n```\n\n\n:::\n:::\n\n\n\n### R Treated\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# Load necessary packages\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(knitr)\nlibrary(kableExtra)\n\nread_data <- function(df)\n{\n  full_path <- paste(\"https://github.com/scunning1975/mixtape/raw/master/\",df, sep = \"\")\n  df <- read_dta(full_path)\n  return(df)\n}\n\ntraining_example <- read_data(\"training_example.dta\") %>% slice(1:20)\n\nggplot(training_example, aes(x=age_treat)) +\n  stat_bin(bins = 10, na.rm = TRUE)\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n### R Control\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# Load necessary packages\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(knitr)\nlibrary(kableExtra)\n\nread_data <- function(df)\n{\n  full_path <- paste(\"https://github.com/scunning1975/mixtape/raw/master/\",df, sep = \"\")\n  df <- read_dta(full_path)\n  return(df)\n}\n\ntraining_example <- read_data(\"training_example.dta\") %>% slice(1:20)\n\nggplot(training_example, aes(x=age_control)) +\n  stat_bin(bins = 10, na.rm = TRUE)\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n### R Matched\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# Load necessary packages\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(knitr)\nlibrary(kableExtra)\n\nread_data <- function(df)\n{\n  full_path <- paste(\"https://github.com/scunning1975/mixtape/raw/master/\",df, sep = \"\")\n  df <- read_dta(full_path)\n  return(df)\n}\n\ntraining_example <- read_data(\"training_example.dta\") %>% slice(1:20)\n\nggplot(training_example, aes(x=age_matched)) +\n  stat_bin(bins = 10, na.rm = TRUE)\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n:::\n\n\n\n\n## Matching   {.smaller background=\"#f2d5bf\"}\n\nIn this example, you are literally finding the units in the control group that have the same age as the units in the treatment group.\n\nYou are exact matching 1-by-1 in this example.\n\nYou have only one covariate, i.e., age.\n\n\n\n\n\n\n\n\n\n\n\n# Distance Matching  {.smaller background=\"#d4b8a3\"}\n\n## Distance Matching  {.smaller background=\"#d4b8a3\"}\n\nThe last example was simple because you could *exact match*.\n\nIf you cannot find one exact match, you need an approximate match. \n\n. . .\n\nIn order to do that, you have to use distance matching.\n\n**Distance matching** minimizes the distance (i.e., how far the covariates are from each other) between the treatment and control groups.\n\n\n\n\n\n\n\n\n## Distance Matching  {.smaller background=\"#d4b8a3\"}\n\n**Euclidean distance** = $|X_i-X_j|=\\sqrt{(X_i-X_j)'(X_i-X_j)}=\\sqrt{\\sum_{n=1}^k(X_{n,i}-X_{n,j})^2}$\n\n![](figs/euclidian.png)\n\n\n\n## Distance Matching  {.smaller background=\"#d4b8a3\"}\n\n**Normalized Euclidean distance** = $|X_i-X_j|=\\sqrt{(X_i-X_j)'\\hat{V}^{-1}(X_i-X_j)}=\\sqrt{\\sum_{n=1}^k\\frac{(X_{n,i}-X_{n,j})}{\\sigma^2_n}}$\n\nThe problem with this measure of distance is that the distance measure itself depends on the **scale of the variables themselves**. \n\nFor this reason, researchers typically will use some modification of the Euclidean distance, such as the **normalized Euclidean distance**, or they’ll use a wholly different alternative distance. \n\nThe normalized Euclidean distance is a commonly used distance, and what makes it different is that the distance of each variable is scaled by the variable’s variance. \n\n\n \n \n \n \n \n## Distance Matching  {.smaller background=\"#d4b8a3\"}\n\n**Mahalanobis  distance** = $|X_i-X_j|=\\sqrt{(X_i-X_j)'\\hat{\\sum_x}^{-1}(X_i-X_j)}$\n\nWhere $\\hat{\\sum_x}$ is the sample covariance matrix of X.\n\n. . . \n\n![](figs/malahanobis_king_nielsen.png)\n\n\n\n\n\n## Distance Matching  {.smaller background=\"#d4b8a3\"}\n\nDistance matching only goes so far...\n\n... **the larger the dimensionality, the harder is to use distance matching**.\n\nAs sample size increases, for a given N of covariates, the matching discrepancies tend to zero.\n\nBut, the more covariates, the longer it takes.\n\n. . . \n\nAt the end of the day, it is preferable to have many covariates, but it is makes distance matching harder.\n\n\n\n\n\n\n\n\n# Coarsened Exact Matching (CER)  {.smaller background=\"#fce0cc\"}\n\n## Coarsened Exact Matching (CER)  {.smaller background=\"#fce0cc\"}\n\nIn coarsened exact matching, something only counts as a match if it exactly matches on each matching variable. \n\n**The “coarsened” part comes in because, if you have any continuous variables to match on, you need to “coarsen” them first by putting them into bins, rather than matching on exact values.**\n\nCoarsening means creating bins. Fewer bins makes exact matches more likely. \n\n. . .\n\nCER is not used much in empirical research in finance. It is used more in the big data realm when you have many variables to match. \n\n\n\n\n\n\n\n# Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n**PSM is one way to matching using many covariates.** \n\n**PSM aggregates all covariates into one score (propensity-score), which is the likelihood of receiving the treatment.**\n\nThe idea is to match units that, based on observables, have the same probability (called propensity-score) of being treated. \n\n. . .\n\nThe idea is to estimate a probit (default in stata) or logit model (fist stage):\n\n$$P(D=1|X)$$\n\n**The propensity-score is the predicted probability of a unit being treated given all covariates X**. The p-score is just a single number.\n\n\n\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\nConsiderations in PSM.\n\n1) How many neighbors to match?\n\n- Nearest neighbor, radius or kernel?\n\n2) With or without replacement?\n\n3) With or without common support?\n\n- *Common support*: imposes a common support by dropping treatment observations whose pscore is higher than the maximum or less than the minimum pscore of the controls.\n\n4) It is expected that, after PSM, you show the overlap of propensity-scores.\n\n\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n[Source](https://sites.google.com/site/econometricsacademy/home)\n\n**The y-axis is the propensity-score**.\n\n![](figs/ani_katchova1.png)\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n[Source](https://sites.google.com/site/econometricsacademy/home)\n\n**Nearest matching:** Find the observation closest to ($min|p_i-p_j|$)\n\n![](figs/ani_katchova3.png)\n\n\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n[Source](https://sites.google.com/site/econometricsacademy/home)\n\n**Kernel matching:** Each treated observation i is matched with several control observations, with weights inversely proportional to the distance between treated and control observations.\n\n![](figs/ani_katchova2.png)\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n[Source](https://sites.google.com/site/econometricsacademy/home)\n\n**Radius matching**: Each treated observation i is matched with control observations j that fall within a specified radius.\n\n$$|p_i-p_j| <r$$\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n[Source](https://sites.google.com/site/econometricsacademy/home)\n\n**Common support:** Restrict matching only based on the common range of propensity scores.\n\n![](figs/ani_katchova5.png)\n\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\nSeems good overlap, but \"good\" is arbitrary.\n\n![](figs/psm1.png)\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\nSeems bad overlap\n\n![](figs/psm2.png)\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\nSeems good overlap, but \"good\" is arbitrary.\n\n![](figs/psm_graph1.png)\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\nSeems bad overlap\n\n![](figs/psm_graph2.png)\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n![](figs/psm_bias.png)\n\n\n\n\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n![](figs/psm_ttest1.png)\n\n\n## Propensity-score matching (PSM)  {.smaller background=\"#f7dfcd\"}\n\n![](figs/psm_ttest2.png)\n\n\n\n\n\n\n\n\n\n\n# Example  {.smaller background=\"#debda4\"}\n\n## Example  {.smaller background=\"#debda4\"}\n\nLet's practice with an example. 185 treated units vs 15,992 control units. \n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# Load necessary packages\n# Load necessary libraries\nlibrary(haven)\nlibrary(psych)\ndata <- read_dta(\"files/cps1re74.dta\")\nsummary_stats <- by(data, data$treat, FUN = function(group) {\n  c(\n    mean = mean(group$age, na.rm = TRUE),\n    variance = var(group$age, na.rm = TRUE),\n    skewness = skew(group$age, na.rm = TRUE),\n    count = length(group$age)\n  )\n})\nsummary_df <- as.data.frame(do.call(rbind, summary_stats))\ncolnames(summary_df) <- c(\"mean\", \"variance\", \"skewness\", \"count\")\nprint(summary_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      mean variance  skewness count\n0 33.22524 121.9968 0.3477684 15992\n1 25.81622  51.1943 1.1063375   185\n```\n\n\n:::\n:::\n\n\n### Python\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"Python\" code-line-numbers=\"true\"}\nimport pandas as pd\nfrom scipy.stats import skew\nimport statsmodels.api as sm\ndata = pd.read_stata(\"files/cps1re74.dta\")\ngrouped_data = data.groupby('treat')['age'].agg(['mean', 'var', lambda x: skew(x, nan_policy='omit'), 'count']).reset_index()\ngrouped_data.columns = ['treat', 'mean', 'variance', 'skewness', 'count']\nprint(grouped_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   treat       mean    variance  skewness  count\n0      0  33.225238  121.996792  0.347801  15992\n1      1  25.816216   51.194301  1.115369    185\n```\n\n\n:::\n:::\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/cps1re74.dta, clear\nqui estpost tabstat age black educ , by(treat) c(s) s(me v sk n) nototal\nesttab . \t,varwidth(20) cells(\"mean(fmt(3)) variance(fmt(3)) skewness(fmt(3)) count(fmt(0))\") noobs nonumber compress \n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(DW Subset of LaLonde Data)\n\n\n\n------------------------------------------------------------\n                                                            \n                          mean  variance  skewness     count\n------------------------------------------------------------\n0                                                           \nage                     33.225   121.997     0.348     15992\nblack                    0.074     0.068     3.268     15992\neduc                    12.028     8.242    -0.423     15992\n------------------------------------------------------------\n1                                                           \nage                     25.816    51.194     1.115       185\nblack                    0.843     0.133    -1.888       185\neduc                    10.346     4.043    -0.721       185\n------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n## Example  {.smaller background=\"#debda4\"}\n\nClearly, the treated group is younger, mainly black, and less educated.\n\nAlso note that the **variance and skewness** of the two subsamples are **different**.\n\nIf we were to use these two subsamples in any econometric analysis **without preprocessing to make them comparable**, we would likely have coefficients biased by **selection bias**.\n\nTherefore, it is important to perform some matching method.\n\nLet's start with Propensity Score Matching (PSM). We will use the simplest matching, that is, without using any additional functions.\n\n\n\n\n\n\n\n\n\n\n## Example  {.smaller background=\"#debda4\"}\n\n**Nearest with noreplacement.**\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# install.packages(\"MatchIt\")\nlibrary(haven)\nlibrary(psych)\nlibrary(MatchIt)\ndata <- read_dta(\"files/cps1re74.dta\")\nmodel <- matchit(treat ~ age + black + educ, data = data, method = \"nearest\")\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nmatchit(formula = treat ~ age + black + educ, data = data, method = \"nearest\")\n\nSummary of Balance for All Data:\n         Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean\ndistance        0.1445        0.0099          1.3615     7.5662    0.4987\nage            25.8162       33.2252         -1.0355     0.4196    0.1863\nblack           0.8432        0.0735          2.1171          .    0.7697\neduc           10.3459       12.0275         -0.8363     0.4905    0.0908\n         eCDF Max\ndistance   0.7741\nage        0.3427\nblack      0.7697\neduc       0.4123\n\nSummary of Balance for Matched Data:\n         Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean\ndistance        0.1445        0.1443          0.0020     1.0039    0.0002\nage            25.8162       25.7081          0.0151     0.9244    0.0073\nblack           0.8432        0.8432          0.0000          .    0.0000\neduc           10.3459       10.4054         -0.0296     0.7190    0.0117\n         eCDF Max Std. Pair Dist.\ndistance   0.0162          0.0029\nage        0.0270          0.1481\nblack      0.0000          0.0000\neduc       0.0432          0.2554\n\nSample Sizes:\n          Control Treated\nAll         15992     185\nMatched       185     185\nUnmatched   15807       0\nDiscarded       0       0\n```\n\n\n:::\n:::\n\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/cps1re74.dta, clear\npsmatch2 treat age black educ , n(1) noreplacement\nsum _weight , d\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(DW Subset of LaLonde Data)\n\n\nProbit regression                                       Number of obs = 16,177\n                                                        LR chi2(3)    = 752.47\n                                                        Prob > chi2   = 0.0000\nLog likelihood = -634.83401                             Pseudo R2     = 0.3721\n\n------------------------------------------------------------------------------\n       treat | Coefficient  Std. err.      z    P>|z|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         age |  -.0379829   .0042976    -8.84   0.000     -.046406   -.0295598\n       black |   1.700675   .0793898    21.42   0.000     1.545074    1.856277\n        educ |  -.0806962   .0142167    -5.68   0.000    -.1085604    -.052832\n       _cons |  -.9031083   .2123282    -4.25   0.000    -1.319264   -.4869526\n------------------------------------------------------------------------------\n\n            psmatch2: weight of matched controls\n-------------------------------------------------------------\n      Percentiles      Smallest\n 1%            1              1\n 5%            1              1\n10%            1              1       Obs                 370\n25%            1              1       Sum of wgt.         370\n\n50%            1                      Mean                  1\n                        Largest       Std. dev.             0\n75%            1              1\n90%            1              1       Variance              0\n95%            1              1       Skewness              .\n99%            1              1       Kurtosis              .\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n\n\n\n\n\n\n## Example  {.smaller background=\"#debda4\"}\n\n**Notice that we are creating weights now**\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# install.packages(\"MatchIt\")\nlibrary(haven)\nlibrary(MatchIt)\ndata <- read_dta(\"files/cps1re74.dta\")\nmodel <- matchit(treat ~ age + black + educ, data = data, method = \"exact\")\nsummary(model$weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.0000  0.0000  0.0000  0.1457  0.0000 52.7952 \n```\n\n\n:::\n:::\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/cps1re74.dta, clear\nqui psmatch2 treat age black educ , kernel\nsum _weight , d\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(DW Subset of LaLonde Data)\n\n            psmatch2: weight of matched controls\n-------------------------------------------------------------\n      Percentiles      Smallest\n 1%     .0024355       .0007862\n 5%     .0024375       .0024348\n10%       .00244       .0024348       Obs              16,177\n25%     .0024517       .0024348       Sum of wgt.      16,177\n\n50%     .0024919                      Mean            .022872\n                        Largest       Std. dev.      .1130791\n75%     .0026476              1\n90%     .0038379              1       Variance       .0127869\n95%     .0876547              1       Skewness       7.604874\n99%            1              1       Kurtosis       64.26276\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n\n\n\n\n\n\n## Example  {.smaller background=\"#debda4\"}\n\n**Now, the descriptive statistics are much closer**\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\nlibrary(haven)\nlibrary(MatchIt)\n#install.packages(\"e1071\")\nlibrary(e1071)\ndata <- read_dta(\"files/cps1re74.dta\")\nmodel <- matchit(treat ~ age + black + educ, data = data, method = \"exact\")\nmatched_data <- match.data(model)\nsummary_stats <- by(matched_data, matched_data$treat, function(x) {\n  c(mean(x$age), var(x$age), skewness(x$age), length(x$age))\n})\n\nresult_df <- data.frame(\n  Treatment = c(\"Control\", \"Treated\"),\n  Mean_Age = sapply(summary_stats, function(x) x[1]),\n  Variance_Age = sapply(summary_stats, function(x) x[2]),\n  Skewness_Age = sapply(summary_stats, function(x) x[3]),\n  Count = sapply(summary_stats, function(x) x[4])\n)\nprint(result_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment Mean_Age Variance_Age Skewness_Age Count\n0   Control 25.58786     39.16294    0.7826941  2191\n1   Treated 25.51807     51.59664    1.1298334   166\n```\n\n\n:::\n:::\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/cps1re74.dta, clear\nqui psmatch2 treat age black educ , kernel\nqui estpost tabstat age black educ [aweight = _weight], by(treat) c(s) s(me v sk n) nototal\nesttab . \t,varwidth(20) cells(\"mean(fmt(3)) variance(fmt(3)) skewness(fmt(3)) count(fmt(0))\") noobs  nonumber compress \n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(DW Subset of LaLonde Data)\n\n\n\n\n------------------------------------------------------------\n                                                            \n                          mean  variance  skewness     count\n------------------------------------------------------------\n0                                                           \nage                     27.033    85.548     1.077     15992\nblack                    0.791     0.165    -1.434     15992\neduc                    10.710     8.146    -0.883     15992\n------------------------------------------------------------\n1                                                           \nage                     25.816    51.194     1.115       185\nblack                    0.843     0.133    -1.888       185\neduc                    10.346     4.043    -0.721       185\n------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n# Entropy Balancing  {.smaller background=\"#fac9a7\"}\n\n## Entropy Balancing  {.smaller background=\"#fac9a7\"}\n\n**Here, instead of matching units, we reweight the observations such that the moments of the distributions (mean, variance, skewness) are similar.**\n\n- The ebalance function implements a reweighting scheme. The user starts by choosing the covariates that should be included in the reweighting. \n\n- For each covariate, the user then specifies a set of balance constraints (in Equation 5) to equate the moments of the covariate distribution between the treatment and the reweighted control group. \n\n- The moment constraints may include the mean (first moment), the variance (second moment), and the skewness (third moment).\n\n**The outcome is a vector containing the weights to weight the observations, such that the weighted average, weighted variance, and weighted skewness of the covariates in control group are similar to those in the treatment group**\n\n\n\n\n\n\n\n\n\n\n## Entropy Balancing  {.smaller background=\"#fac9a7\"}\n\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\nlibrary(haven)\n#install.packages(\"ebal\")\nlibrary(ebal)\ndata <- read_dta(\"files/cps1re74.dta\")\ntreatment <-cbind(data$treat)\nvars <-cbind(data$age, data$educ, data$black)\neb <- ebalance(treatment, vars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConverged within tolerance \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# means in treatment group data\napply(vars[treatment==1,],2,mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.8162162 10.3459459  0.8432432\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# means in reweighted control group data\napply(vars[treatment==0,],2,weighted.mean,w=eb$w)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.8163688 10.3460391  0.8431526\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# means in raw data control group data\napply(vars[treatment==0,],2,mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 33.22523762 12.02751376  0.07353677\n```\n\n\n:::\n:::\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/cps1re74.dta, clear\nebalance treat age black educ, targets(3)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(DW Subset of LaLonde Data)\n\n\n\nData Setup\nTreatment variable:   treat\nCovariate adjustment: age black educ (1st order). age black educ (2nd order). a\n> ge black educ (3rd order).\n\n\nOptimizing...\nIteration 1: Max Difference = 580799.347\nIteration 2: Max Difference = 213665.688\nIteration 3: Max Difference = 78604.7628\nIteration 4: Max Difference = 28918.6249\nIteration 5: Max Difference = 10640.1108\nIteration 6: Max Difference = 3915.82197\nIteration 7: Max Difference = 1442.09731\nIteration 8: Max Difference = 532.07826\nIteration 9: Max Difference = 197.376777\nIteration 10: Max Difference = 74.6380533\nIteration 11: Max Difference = 29.9524313\nIteration 12: Max Difference = 11.4337344\nIteration 13: Max Difference = 4.43722698\nIteration 14: Max Difference = 1.76899046\nIteration 15: Max Difference = .420548538\nIteration 16: Max Difference = .037814194\nIteration 17: Max Difference = .001164231\nmaximum difference smaller than the tolerance level; convergence achieved\n\n\nTreated units: 185     total of weights: 185\nControl units: 15992   total of weights: 185\n\n\nBefore: without weighting\n\n             |              Treat              |        Control       \n             |      mean   variance   skewness |      mean   variance \n-------------+---------------------------------+----------------------\n         age |     25.82      51.19      1.115 |     33.23        122 \n       black |     .8432      .1329     -1.888 |    .07354     .06813 \n        educ |     10.35      4.043     -.7212 |     12.03      8.242 \n\n             |  Control  \n             |  skewness \n-------------+-----------\n         age |     .3478 \n       black |     3.268 \n        educ |    -.4233 \n\n\nAfter:  _webal as the weighting variable\n\n             |              Treat              |        Control       \n             |      mean   variance   skewness |      mean   variance \n-------------+---------------------------------+----------------------\n         age |     25.82      51.19      1.115 |      25.8      51.17 \n       black |     .8432      .1329     -1.888 |     .8421       .133 \n        educ |     10.35      4.043     -.7212 |     10.34       4.04 \n\n             |  Control  \n             |  skewness \n-------------+-----------\n         age |     1.122 \n       black |    -1.877 \n        educ |    -.7121 \n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n\n\n## Entropy Balancing  {.smaller background=\"#fac9a7\"}\n\n\n::: panel-tabset\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/cps1re74.dta, clear\nqui ebalance treat age black educ, targets(3)\nqui estpost tabstat age black educ [aweight = _webal], by(treat) c(s) s(me v sk n) nototal\nesttab . \t,varwidth(20) cells(\"mean(fmt(3)) variance(fmt(3)) skewness(fmt(3)) count(fmt(0))\") noobs  nonumber compress \n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(DW Subset of LaLonde Data)\n\n\n\n\n------------------------------------------------------------\n                                                            \n                          mean  variance  skewness     count\n------------------------------------------------------------\n0                                                           \nage                     25.801    51.167     1.122     15992\nblack                    0.842     0.133    -1.877     15992\neduc                    10.340     4.040    -0.712     15992\n------------------------------------------------------------\n1                                                           \nage                     25.816    51.194     1.115       185\nblack                    0.843     0.133    -1.888       185\neduc                    10.346     4.043    -0.721       185\n------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n# DiD Introduction {.smaller background=\"#c4f5d7\"}\n\n## DiD Introduction  {.smaller background=\"#c4f5d7\"}\n\nLet's introduce DiD using the most famous example in the topic: John Snow’s 1855 findings that demonstrated to the world that cholera was spread by fecally-contaminated water and not via the air (Snow 1855)\n\n- Snow compared the periods of 1849 and 1854 to analyze the impact of a  change in London's water supply dynamics. \n- Various water companies, each drawing water from different sections of the Thames river, served the city's water needs. \n- The downstream areas of the Thames, where some companies sourced their water, were susceptible to contamination due to the disposal of various substances, including fecal matter from cholera-infected individuals. \n- In the interim between 1849 and 1854, a pivotal policy was implemented: the Lambeth Company was mandated by an Act of Parliament to relocate its water intake upstream of London.\n\n\n\n\n\n## DiD Introduction  {.smaller background=\"#c4f5d7\"}\n\n**This is what happened.**\n\n| Region Supplier                        | Death Rates 1849 | Death Rates 1854 |\n|----------------------------------------|------------------|------------------|\n| Non-Lambeth Only (Dirty)               | 134.9            | 146.6            |\n| Lambeth + Others (Mix Dirty and Clean) | 130.1            | 84.9             |\n\n. . . \n\nThe specific DID estimate we can get here is:\n\n- $(84.9-130.1)-(146.9-134.9)=-57.2$.\n\nThis resembles a \"modern\" DiD. \n\n\n\n\n\n\n\n\n# Shocks {.smaller background=\"#95c9a9\"}\n\n## Shocks  {.smaller background=\"#95c9a9\"}\n\n**Shock-based designs use an external shock to limit selection bias. **\n\nThey are very hard to find, but if you do, you can reasonably estimate causal effects.\n\nThey are sources of exogenous variations in the X, which are crucial to causality when we have some of the problems discussed before. \n\nA shock is often considered the first-best solution to causal inference (randomized control trials are the second-best).\n\n. . . \n\nIn social sciences, we cannot have randomized control trials. It is not feasible to have experiments.\n\nThat is why we often explore the idea of \"Natural experiments\" or \"Natural shocks\" (I often use the terms interchangeably)\n\n\n\n\n\n\n\n## Shocks  {.smaller background=\"#95c9a9\"}\n\nA **Natural experiment** is an exogenous variation that change a variable in a random subset of firms. \n\n- Regulations, laws, etc.\n- Natural disasters.\n- Sudden death of CEOs or a product, etc.\n- The gender of a newborn.\n\n\nBecause the variation that occur in x is truly exogenous, the CMI holds and thus we can infer causality.\n\n\n\n\n\n\n\n## Shocks  {.smaller background=\"#95c9a9\"}\n\nA good shock has some conditions [source](https://cfr.pub/published/papers/cfr-0036.pdf):\n\n1) **Shock Strength**: The shock is strong enough to significantly change firm behavior or incentives.\n\n. . .\n \n2) **Exogenous Shock**: The shock came from “outside” the system one is studying.\n\n  - Treated firms did not choose whether to be treated, \n  - cannot anticipate the shock, \n  - the shock is expected to be permanent, and \n  - there is no reason to believe that which firms were treated depends on unobserved firm characteristics.\n  \nIf the shock is exogenous, or appears to be, we are less worried that unobservables might be correlated with both assignment to treatment and the potential outcomes, and thus generate omitted variable bias. \n\nShock exogeneity should be defended, not just assumed.\n\n\n\n\n\n\n\n## Shocks  {.smaller background=\"#95c9a9\"}\n\nA good shock has some conditions [source](https://cfr.pub/published/papers/cfr-0036.pdf):\n\n3) **“As If Random” Assignment**: The shock must separate firms into treated and controls in a manner which is close to random.\n\n. . .\n\n4) **Covariate balance:** The forcing and forced variables aside, the shock should produce reasonable covariate balance between treated and control firms, including “common support” (reasonable overlap between treated and control firms on all covariates). \n\nSomewhat imperfect balance can be address with balancing methods, but severe imbalance undermines shock credibility, even if the reason for imbalance is not obvious. Covariate balance should be reported.\n\n\n\n\n\n\n\n## Shocks  {.smaller background=\"#95c9a9\"}\n\nA good shock has some conditions [source](https://cfr.pub/published/papers/cfr-0036.pdf):\n\n5) **Only-Through Condition(s):** We must have reason to believe that the apparent effect of the shock on the outcome came only through the shock (sometimes, through a specific channel). \n\nThe shock must be “isolated”, there must be no other shock, at around the same time, that could also affect treated firms differently than control firms. \nAnd if one expects the shock to affect outcomes through a particular channel, the shock must also affect the outcome only through that channel.\n\n. . .\n\nIn IV analysis, this is called an **“exclusion restriction”** or **“only-through condition\"**, because one assumes away (excludes) other channels.\n\n\n\n\n\n\n## Shocks  {.smaller background=\"#95c9a9\"}\n\nThe idea of a natural shock is often mixed with the difference-in-differences (DiD) design.\n\nIt is more common that it should that people refer to shocks when they want to refer to DiD. \n\nA Did design explores a Natural shock to estimate causal effects.\n\n**A good shock generates, by nature, random assignment**.\n\n\n\n\n\n\n\n\n\n## Remember  {.smaller background=\"#693d3a\"}\n\n**Remember:**\n\nWhen dealing with **causal inference**, we have to find ways to approximate what the hidden potential outcome of the treated units is. \n\nThat is, the challenge in identifying causal effects is that the untreated potential outcomes, $Y_{i,0}$, are never\nobserved for the treated group ($D_i= 1$). The \"second\" term in the following equation:\n\nATET = $\\frac{1}{N} (E[Y_{i,1}|D_i=1] - E[Y_{i,0}|D_i=1])$\n\nWe need an empirical design to **\"observe\"** what we do not really observe (i.e., the counterfactual). \n\n\n\n\n\n\n\n# Single differences  {.smaller background=\"#a4baac\"}\n\n## Single differences  {.smaller background=\"#a4baac\"}\n\nThere are two single differences we can use to estimate the causal effect of a treatments (i.e., a shock).\n\n**1) Single Cross-Sectional Differences After Treatment**\n\n**2) Single Time-Series Difference Before and After Treatment**\n\n\n\n\n\n\n\n## Single differences  {.smaller background=\"#a4baac\"}\n\n**1) Single Cross-Sectional Differences After Treatment**\n\nOne approach to estimating a parameter that summarizes the treatment effect is to compare the post-treatment outcomes of the treatment and control groups. \n\nThis method is often used when there is no data available on pre-treatment outcomes.\n\nIt takes the form:\n\n$$y=\\beta_0+\\beta_1d_i+\\epsilon$$\n\nwhere $d_i$ is a dummy marking the units that are treated. The treatment effect is given by $\\beta_1$\n\nThis is a cross-sectional comparison, using only post-treatment values.\n\n\n\n\n\n\n\n\n## Single differences  {.smaller background=\"#a4baac\"}\n\n**1) Single Cross-Sectional Differences After Treatment**\n\nYou may add the interaction between the treatment dummy and the years.\n\n$$y=\\beta_0+\\beta_1d_i\\times year_1+\\beta_2d_i\\times year_2 +\\beta_3d_i\\times year_3+ . . . +\\epsilon$$\n\nThis design allows the treatment effect to vary over time by interacting the treatment dummy with period dummies.\n\n\n\n\n. . . \n\n\n**What is the endogeneity concern here?**\n\n. . .\n\nThe endogeneity concern is that these firms’ $y$ were different and could become more different between the treated and control groups even if the shock had not happened. \n\nThat is, there is something in the residual that explains the differences in $y$ that is correlated with the $d$.\n\n\n\n\n\n\n\n\n\n## Single differences  {.smaller background=\"#a4baac\"}\n\n**2) Single Time-Series Difference Before and After Treatment**\n\nA second way to estimate the treatment effect is to compare the outcome after the treatment with the outcome before the treatment for **just those units that are treated.**\n\nThe difference from before is that you have data before the treatment, but you only have data for the treated units.\n\n$$y=\\beta_0+\\beta_1 time+\\epsilon$$\n\nwhere $time$ marks the years after the treatment. The treatment effect is given by $\\beta_1$\n\n\n\n\n\n\n## Single differences  {.smaller background=\"#a4baac\"}\n\n**2) Single Time-Series Difference Before and After Treatment**\n\nYou can also estimate a multi-year regression.\n\n$$y=\\beta_0+\\beta_1year_1 +\\beta_2\\times year_2 +\\beta_3\\times year_3+ . . . +\\epsilon$$\n\n. . . \n\n\n**What is the endogeneity concern here?**\n\n. . .\n\nThe endogeneity concern is that these firms’ $y$ could have changed over the period of observation even if the shock had not happened. \n\nThat is, there is something in the error term that explains $y$ that is correlated with the $year$ dummies.\n\n\n\n\n\n## Single differences  {.smaller background=\"#a4baac\"}\n\nThe combination of the  **1) Single Cross-Sectional Differences After Treatment** and **2) Single Time-Series Difference Before and After Treatment** is called **Difference-in-Differences**.\n\n\n\n\n\n\n\n\n# Difference-in-Differences {.smaller background=\"#8bc9a2\"}\n\n## Difference-in-Differences  {.smaller background=\"#8bc9a2\"}\n\nThis is one of the most popular methods in social sciences for estimating causal effects in non-experimental settings.\n\nThe literature is exploding over the recent years.\n\n. . . \n\nThere is one group that is treated, another is the control. \n\nThere are two periods of time, before and after the treatment.\n\nAnd the treated group receives the treatment in the second period.\n\n**The key identifying assumption is that the average outcome among the treated and comparison populations would have followed “parallel trends” in the absence of treatment.**\n\n\n\n## Difference-in-Differences  {.smaller background=\"#8bc9a2\"}\n\n\n*The two single difference estimators complement one another.*\n\n*The cross-sectional comparison avoids the problem of omitted trends by comparing two groups over the same time period.*\n\n*The time series comparison avoids the problem of unobserved differences between two different groups of firms by looking at the same firms before and after the change.*\n\n*The double difference, difference-in-differences (DD), estimator combines these two estimators to take advantage of both estimators’ strengths.* \n\n([Roberts and Whited, 2014](https://doi.org/10.1016/B978-0-44-453594-8.00007-0))\n\n\n\n\n\n\n## Difference-in-Differences  {.smaller background=\"#8bc9a2\"}\n\n\nDifference-in-differences methods overcome the identification challenge via assumptions that allow us to impute the mean counterfactual untreated outcomes for the treated group by using \n\n- (a) the change in outcomes for the untreated group and \n- (b) the baseline outcomes for the treated group. \n\nThe key assumption for identifying the causal effect is the **parallel trends assumption**, which intuitively states that **the average outcome for the treated and untreated units would have evolved in parallel if treatment had not occurred**.\n\n**Assumption 1 (Parallel Trends).**\n\n$E[Y_{i,1,t=2}-Y_{i,0,t=1}|D_i=1] = E[Y_{i,1,t=2}-Y_{i,0,t=1}|D_i=0]$\n\n\nIn other words: **this condition means that in the absence of treatment, the average change in the $y$ would have been the same for both the treatment and control groups.**\n\n\n\n\n\n\n\n\n\n## Difference-in-Differences  {.smaller background=\"#8bc9a2\"}\n\n**The counterfactual is determined by the assumption of a parallel trend between the treated and control groups.** **[MM](https://www.masteringmetrics.com/)**\n\n\n![](figs/did1.png) \n\n\n\n\n## Difference-in-Differences  {.smaller background=\"#8bc9a2\"}\n\n![](figs/slides4-did.png) \n\n\n\n\n## Difference-in-Differences  {.smaller background=\"#8bc9a2\"}\n\nInserting more periods.\n\n![](figs/did2.png) \n\n\n\n\n## Difference-in-Differences  {.smaller background=\"#8bc9a2\"}\n\nA more realistic example. ([The effect](https://theeffectbook.net/ch-DifferenceinDifference.html))\n\n\n![](figs/theeffect1.png)\n\n\n\n\n\n\n## Difference-in-Differences  {.smaller background=\"#8bc9a2\"}\n\n\n**Assumption 2 (No anticipatory effects).**\n\n*The treatment has no causal effect prior to its implementation.*\n\n$$Y_{i,0,t=1}=Y_{i,1,t=1}$$\n\nPrior to the treatment (t=1), there is no effect of the treatment.\n\n\n\n\n\n\n\n\n\n# Estimation  {.smaller background=\"#c6f7ec\"}\n\n## Estimation   {.smaller background=\"#c6f7ec\"}\n\nLet's see how to implement a DiD model. The canonical DiD model is the followin:\n\n$$y_{i,t} = \\beta_0 + \\beta_1 time_t + \\beta_2 treated_i  + \\beta_3 treated_i \\times time_t + \\epsilon_{i,t}$$\n\nWhere:\n\n$treated_i$ is a dummy marking the units that received the treatment.\n\n$time_t$ is a dummy marking the year of the treatment and the years after.\n\n\n\n\n\n\n## Estimation   {.smaller background=\"#c6f7ec\"}\n\nLet's see how to implement a DiD model. The canonical DiD model is the followin:\n\n$$y_{i,t} = \\beta_0 + \\beta_1 time_t + \\beta_2 treated_i  + \\beta_3 treated_i \\times time_t + \\epsilon_{i,t}$$\n\n\n$\\beta_0$ is the **average $y_{i,t}$** for the **control units before the treatment ($time_t$ =0 and $treated_i$ = 0)**.\n\n$\\beta_0+\\beta_1$ is the **average $y_{i,t}$** for the **control units after the treatment ($time_t$ =1 and $treated_i$ = 0)**.\n\n$\\beta_0+\\beta_2$ is the **average $y_{i,t}$** for the **treated units before the treatment ($time_t$ =0 and $treated_i$ = 1)**.\n\n$\\beta_0+\\beta_1+\\beta_2+\\beta_3$ is the **average $y_{i,t}$** for the **treated units after the treatment ($time_t$ =1 and $treated_i$ = 1)**.\n\n\n\n\n## Estimation   {.smaller background=\"#c6f7ec\"}\n\n+------------------+-----------------------------------+---------------------+---------------------+\n|                  |   Post-treat. (1)                 |  Pre-treat. (2)     |  **Diff. (1-2)**    |\n+------------------+-----------------------------------+---------------------+---------------------+\n|   Treated (a)    | $\\beta_0+\\beta_1+\\beta_2+\\beta_3$ | $\\beta_0+\\beta_2$   |**$\\beta_1+\\beta_3$**|\n+------------------+-----------------------------------+---------------------+---------------------+\n|  Control (b)     | $\\beta_0+\\beta_1$                 |  $\\beta_0$          | **$\\beta_1$**       |\n+------------------+-----------------------------------+---------------------+---------------------+\n| **Diff. (a-b)**  | **$\\beta_2+\\beta_3$**             |  **$\\beta_2$**      | **$\\beta_3$**       |\n+------------------+-----------------------------------+---------------------+---------------------+\n\n\n**This is why we call difference-in-differences.**\n\n**$\\beta_3$** gives us an estimate of the treatment effect on the treated units (ATE).\n\nThis is very popular because you can run as a regression.\n\n. . . \n\nMany papers simply show this table as final result.\n\nHowever, it is also possible that you include additional covariates (i.e., controls) in a DiD design. \n\nYou can also modify this to test the timing of the treatment (discussed later).\n\n\n\n\n\n\n\n\n\n\n# Controls in DiD  {.smaller background=\"#d5f5ee\"}\n\n## Controls in DiD  {.smaller background=\"#d5f5ee\"}\n\nIf you add controls, you have something in the form:\n\n$$y_{i,t} = \\beta_0 + \\beta_1 time_t + \\beta_2 treated_i  + \\beta_3 treated_i \\times time_t + \\beta_4x_{1,i,t}+ \\beta_5x_{2,i,t}+ ...+ \\epsilon_{i,t}$$\n\n. . . \n\n::: {.callout-important}\nBad Controls problem: Never add a control that is also affected by the treatment. \n:::\n\n. . . \n\n::: {.callout-tip}\nUsing pre-treatment values is good practice. \n:::\n\nIf you are including a *good control*, you should get lower standard deviations of the estimated effects.\n\n\n\n\n\n## Controls in DiD  {.smaller background=\"#d5f5ee\"}\n\nOne way of adding more controls is by adding FEs.\n\n$$y_{i,t} = \\beta_0 + \\beta_1 time_t + \\beta_2 treated_i  + \\beta_3 treated_i \\times time_t + FirmFE+ YearFE + \\epsilon_{i,t}$$\n\nThey help control for unobserved heterogeneity at the firm-level and in each year.\n\n. . . \n\n**But what do $\\beta_1$ and  $\\beta_2$ mean now?**\n\n. . .\n \n**Answer:** They are perfectly correlated with the $FirmFE$ and $YearFE$, respectively.\n\nReason: because they don't vary across each firm and year, respectively. \n\nThe software will most likely drop one $FirmFE$ and one $YearFE$, thus $\\beta_1$ and  $\\beta_2$ mean nothing.\n\n. . .\n\nI am guilty of this mistake because a referee asked and I couldn't reply properly.\n\n\n\n\n\n\n\n\n## Controls in DiD  {.smaller background=\"#d5f5ee\"}\n\nYou will be better off if you estimate:\n\n$$y_{i,t} = \\beta_0 + \\beta_3 treated_i \\times time_t + FirmFE+ YearFE + \\epsilon_{i,t}$$\n\nThis is called a **generalized DiD**.\n\nThe $FirmFE$ allow that each firm has one intercept (i.e., one average $y_{i,t}$).\n\nThe $YearFE$ accommodate a potential shock in $y_{i,t}$ in each year.\n\n\n\n\n\n\n\n\n\n## Controls in DiD  {.smaller background=\"#d5f5ee\"}\n\nAdditionally, adding *good* controls can be helpful to maintain the shock **exogenous (i.e., random) after controlling by X.**\n\n. . . \n\nImagine that a financial shock is more likely to affect high leveraged firms than low-leverage ones.\n\n1) the shock will not change the leverage decision of each firm.\n\n2) we believe that high leveraged firms will have a different $y_{i,t}$ after the treatment.\n\nYou may add leverage as a control to make sure the shock is random given the firms' levels of leverage.\n\n. . .\n\nIf you may believe that the leverage will change after the treatment, you can use pre-treatment values (interacted with the time dummies).\n\nIn this case, you are controlling for the pre-treatment condition but are not including the bias that might come due to changes in leverage after the treatment.\n\n\n\n\n\n\n\n## Controls in DiD  {.smaller background=\"#d5f5ee\"}\n\n*If assignment is random, then including additional covariates should have a negligible effect on the estimated treatment effect.*\n\n*Thus, a large discrepancy between the treatment effect estimates with and without additional controls raises a red flag.* \n\n*If assignment to treatment and control groups is not random but dictated by an observable rule, then controlling for this rule via covariates in the regression satisfies the conditional mean zero assumption required for unbiased estimates.* \n\n*Regardless of the motivation, it is crucial to remember that any covariates included as controls must be unaffected by the treatment, a condition that eliminates other outcome variables and restricts most covariates to pre-treatment values.*\n\n([Roberts and Whited, 2014](https://doi.org/10.1016/B978-0-44-453594-8.00007-0))\n \n \n\n\n\n\n\n# Comment about DiD {.smaller background=\"#aecfc7\"}\n\n## Comment about DiD  {.smaller background=\"#aecfc7\"}\n\n([The effect](https://theeffectbook.net/ch-DifferenceinDifference.html))\n\n\n*Parallel trends means we have to think very carefully about how our dependent variable is measured and transformed.*\n\n*Because parallel trends is an assumption about the size of a gap remaining constant, which means something different depending on how you measure that gap.*\n\n*For example, if parallel trends holds for dependent variable $Y$, then it doesn’t hold for $ln(y)$, and vice versa*\n\n. . .\n\n*For example, say that in the pre-treatment period $y$ is 10 for the control group and 20 for the treated group. In the post-treatment period, in the counterfactual world where treatment never happened,$y$ would be 15 for the control group and 25 for the treated group. Gap of $20-10=10$  before, and $25-15=10$ after. Parallel trends holds!*\n\n. . . \n\n*However: $Ln(20)-ln(10)=.693$  before, and $ln(25)-ln(15)=.51$ after. *\n\n\n\n\n\n\n\n\n\n\n# Example of DiD  {.smaller background=\"#98b8b0\"}\n\n## Example of DiD  {.smaller background=\"#98b8b0\"}\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\n# Load the necessary library\nlibrary(foreign)\ndata <- read.dta(\"files/kielmc.dta\")\ndata$y81_nearinc <- data$y81 * data$nearinc\nmodel1 <- lm(rprice ~ y81 + nearinc + y81_nearinc, data = data)\nmodel2 <- lm(rprice ~ y81 + nearinc + y81_nearinc + age + agesq, data = data)\nmodel3 <- lm(rprice ~ y81 + nearinc + y81_nearinc + age + agesq + intst + land + area + rooms + baths, data = data)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rprice ~ y81 + nearinc + y81_nearinc + age + agesq + \n    intst + land + area + rooms + baths, data = data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-76721  -8885   -252   8433 136649 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.381e+04  1.117e+04   1.237  0.21720    \ny81          1.393e+04  2.799e+03   4.977 1.07e-06 ***\nnearinc      3.780e+03  4.453e+03   0.849  0.39661    \ny81_nearinc -1.418e+04  4.987e+03  -2.843  0.00477 ** \nage         -7.395e+02  1.311e+02  -5.639 3.85e-08 ***\nagesq        3.453e+00  8.128e-01   4.248 2.86e-05 ***\nintst       -5.386e-01  1.963e-01  -2.743  0.00643 ** \nland         1.414e-01  3.108e-02   4.551 7.69e-06 ***\narea         1.809e+01  2.306e+00   7.843 7.16e-14 ***\nrooms        3.304e+03  1.661e+03   1.989  0.04758 *  \nbaths        6.977e+03  2.581e+03   2.703  0.00725 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19620 on 310 degrees of freedom\nMultiple R-squared:   0.66,\tAdjusted R-squared:  0.6491 \nF-statistic: 60.19 on 10 and 310 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse \"files/kielmc.dta\", clear\ngen y81_nearinc = y81 * nearinc\neststo:qui reg rprice y81 nearinc y81_nearinc \neststo:qui reg rprice y81 nearinc y81_nearinc age agesq \neststo:qui reg rprice y81 nearinc y81_nearinc age agesq intst land area rooms baths\nesttab , compress\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(est1 stored)\n\n(est2 stored)\n\n(est3 stored)\n\n\n-------------------------------------------------\n                 (1)          (2)          (3)   \n              rprice       rprice       rprice   \n-------------------------------------------------\ny81          18790.3***   21321.0***   13928.5***\n              (4.64)       (6.19)       (4.98)   \n\nnearinc     -18824.4***    9397.9       3780.3   \n             (-3.86)       (1.95)       (0.85)   \n\ny81_near~c  -11863.9     -21920.3***  -14177.9** \n             (-1.59)      (-3.45)      (-2.84)   \n\nage                       -1494.4***    -739.5***\n                         (-11.33)      (-5.64)   \n\nagesq                       8.691***     3.453***\n                          (10.25)       (4.25)   \n\nintst                                   -0.539** \n                                       (-2.74)   \n\nland                                     0.141***\n                                        (4.55)   \n\narea                                     18.09***\n                                        (7.84)   \n\nrooms                                   3304.2*  \n                                        (1.99)   \n\nbaths                                   6977.3** \n                                        (2.70)   \n\n_cons        82517.2***   89116.5***   13807.7   \n             (30.26)      (37.04)       (1.24)   \n-------------------------------------------------\nN                321          321          321   \n-------------------------------------------------\nt statistics in parentheses\n* p<0.05, ** p<0.01, *** p<0.001\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n# Regression Discontinuity Design (RDD) {.smaller background=\"#e3e2b8\"}\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\n**The regression-discontinuity (RD) research design is a quasi experimental method.**\n\nHere the *treatment* is not a binary as before. \n\n**Treated units are assigned based on a cutoff score of a continuous variable.**\n\n. . .\n\nIn a RDD the treatment assignment is not random...\n\n... but it is based in the value of an observed covariate, in which the units lie on either side of the threshold.\n\n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\n**[Example Mastering Metrics](https://www.masteringmetrics.com/):**\n\n- Age for drinking is 18 in Brazil. \n\nWhy prohibiting younger than 18?\n\nThe theory behind this effort is that legal drinking at age 18 discourages binge drinking and promotes a culture of mature alcohol consumption. \n\nThe cutoff splits who can drink and who can't.\n\n\n\n\n\n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\nThe name RDD comes from a *jump*, a discontinuity that occurs in a continuous variable.\n\nIn its simplest form, the design has a:\n\n- The assignment variable (e.g., age), \n\n- Two groups (above and below the cutoff),\n\n- The outcome variable.\n\n- You may include nonlinearities and control variables. \n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\nRDD is:\n\n$$D_i = 1(x_i>c) \\;$$\n\nwhere:\n\n- $$\\;D = 1 \\; if \\;X \\;_i>c $$ \n\n- $$\\;D = 0 \\; if \\;X \\;_i<c $$\n\n\n$X$ is called the forcing variable because it \"forces\" units into treatment or control groups.\n\n$X$ may be correlated with $Y_1$ or $Y_0$, so simply comparing treated and control units would not provide causal effects\n\nHowever, if the units are randomly assigned into treatment around the cutoff, we would have causal effects.\n\n\n\n\n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\nThe main assumption that allows using RDD as a causal method is that\n\n**Next to the cut, the participants are similar. The only difference is that one individual is in each of the \"sides\".** [Source](http://dx.doi.org/10.1016/B978-0-08-097086-8.44049-3)\n\n![](figs/rdd0.png){width=60%  height=60%}\n\n\n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\n- The cutoff value **occurs at 50**\n\n- What are the differences between someone that scores 49.99 and 50.01 in the X variable?\n\n- The intuition is that these individuals are similar and comparable.\n\nIn the absence of **treatment**, the assumption is that the solid line would \"continue\" with the same inclination and values. \n\nThere is a discontinuity, however. This implies that the pretreatment  in the absence of the treatment should be the dashed line.\n\nThe discontinuity is the causal effect of X (at the cutoff) to Y.\n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\n*Unlike the matching and regression strategies based on treatment-control comparisons conditional on covariates, the validity of RDD is based on our willingness to extrapolate across values of the running variable, at least for values in the neighborhood of the cutoff at which treatment switches on.* [MM](https://www.masteringmetrics.com/)\n\n\n\n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\n**Again the drinking example:**\n\n\n**In the US it is 21 years (age & alcohol).** **[Example Mastering Metrics](https://www.masteringmetrics.com/):**\n\n*Notice the x-axis.*\n\n![](figs/rdd1.png)\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\n**In the US it is 21 years.** **[Example Mastering Metrics](https://www.masteringmetrics.com/):**\n\n*Notice the x-axis.*\n\n![](figs/rdd2.png)\n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\nExamples [Almeida et al 2016](https://doi.org/10.1016/j.jfineco.2015.08.008)\n\n\n![](figs/almeida.png)\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\nExamples [Flammer 2015](https://doi.org/10.1287/mnsc.2014.2038)\n\n\n![](figs/flammer.png)\n\n\n\n\n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\nThis is (legally, it should be) an example of a **Sharp RDD**\n\nA **Sharp RDD** occurs when the cutoff is mandatory. There are no exceptions. In this case, there are no 17 years old drinking and driving. \n\nThe treatment is\n\n$$D_a= 1, \\;if \\;a \\;>=\\; 18, \\;0 \\;if \\;a\\; <\\; 18$$ \n\n\n. . . \n\nThe alternative is a **fuzzy RDD**, which occurs when there is some misassignment.\n\n- People from under the cut also receiving the treatment.\n- Ex. students that receive 5,96 usually are *approved* in a course (this is a misassignment).\n- To estimate a Fuzzy RDD, you can use the treatment as an instrumental variable (Angrist & Pischke, 2009).  \n\n\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\n**fuzzy RDD** ([The effect](https://theeffectbook.net/ch-DifferenceinDifference.html) )\n\n\n![](figs/fuzzy.png)\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\n**fuzzy RDD** \n\n*Compliers*: Takes treatment if above threshold but not if below threshold.\n\n*Always-Takers*: Always takes the treatment, ignores the cut.\n\n*Never-Takers*: Never takes the treatment, ignores the cut.\n\n*Defiers*: Takes treatment if below the threshold, does not take the treatment if above the threshold.\n\n\n\n\n## Regression Discontinuity Design (RDD)   {.smaller background=\"#e3e2b8\"}\n\nThings that are \"good\" to a RDD.\n\n- Age \n- Dates (you need 6 years to start school, 5,99 years is not allowed)\n  - Great example: Most of NHL players are those with anniversaries just after the enrollment date\n- Ranking systems\n- Location (when people cannot \"move\" easily)\n\n\n\n\n\n\n# Estimation {.smaller background=\"#d4d3bc\"}\n\n\n## Estimation   {.smaller background=\"#d4d3bc\"}\n\nA **Sharp RDD** can take the form of:\n\n$$Y_i = \\alpha + \\beta_1 D_a + \\beta_2 \\tilde{x}_1 + \\epsilon$$\n\nWhere $D_a$ is the treatment based on the cutoff.\n\n$x$ is the running variable (the difference between the actual $X$ and the cutoff in $X_0$).\n\n- For instance, months until the 18 years birthday.\n\n- We can also use the notation: $\\tilde{X}=x-x_0$ regarding the difference. \n\n\n\n\n\n\n\n## Estimation   {.smaller background=\"#d4d3bc\"}\n\nYou also should trim the sample to a reasonable window around the cutoff $c$ \n\n- Something like: $c-h<X_i<c+h$, where $h$ is a positive value that determines the window\n\n- There is no theoretical solution to how big should $h$ be. It invites robustness tests.\n\n\n\n## Estimation   {.smaller background=\"#d4d3bc\"}\n\n**Final Step:**\n\nDecide on the model of E[Y|X]:\n\n- linear in both \"sides\" with same slope\n\n- linear with different slopes\n\n- non-linear\n\n\n\n**Tip**: always execute a visual inspection to check which model os appropriate.\n\nAlso, always estimate different models and discuss the results.\n\n\n\n\n\n\n## Estimation   {.smaller background=\"#d4d3bc\"}\n\n**fuzzy RDD** \n\n\n$$Y_i = \\alpha + \\beta_1 D_a + \\beta_2 \\tilde{x}_1 + \\beta_3(Z \\times \\tilde{x}_1) \\epsilon$$\n\nWhere Z is 1 if unit is above the cut or 0 if unit is below the cut.\n\nNotice that D is not equal to Z, in these cases.\n\n\n\n\n\n\n\n\n\n# RDD Nonlinearities  {.smaller background=\"#f2f1d5\"}\n\n## RDD Nonlinearities   {.smaller background=\"#f2f1d5\"}\n\n\n**[Example Mastering Metrics](https://www.masteringmetrics.com/):**\n\nThis is a linear relationship, with the same slopes.\n\n![](figs/rdd3.png)\n\n$$E[Y|X,D] = \\alpha + \\beta_1 \\times D + \\beta_2 \\times \\tilde{X}$$\n\n\n\n## RDD Nonlinearities   {.smaller background=\"#f2f1d5\"}\n\n\n[The effect](https://theeffectbook.net/ch-DifferenceinDifference.html) This is a linear relationship, with different  slopes.\n\n![](figs/rdd_diff_slope.png)\n\n\n\n\n\n\n\n\n\n\n## RDD Nonlinearities   {.smaller background=\"#f2f1d5\"}\n\n**[Example Mastering Metrics](https://www.masteringmetrics.com/):**\n\nThis is a nonlinear relationship.\n\n![](figs/rdd4.png)\n\n\n\n\n\n\n\n\n\n\n## RDD Nonlinearities   {.smaller background=\"#f2f1d5\"}\n\n**[Example Mastering Metrics](https://www.masteringmetrics.com/):**\n\n Is the relationship linear or nonlinear here? If you misjudge the relationship, it will be hard to tell a story credibly.\n\n![](figs/rdd5.png)\n\n\n\n\n\n\n\n\n\n## RDD Nonlinearities   {.smaller background=\"#f2f1d5\"}\n\n**The takeaway:** **RDD is a graphical method. You need to show the graphs**.\n\n**Nobody will believe your story without the correct specification of the model**.\n\n. . .\n\nIn the first case:\n\n\n$$Y_i = \\alpha + \\beta_1 D_a + \\beta_2 x_1 + \\epsilon$$\n\nIn the second case:\n\n$$Y_i = \\alpha + \\beta_1 D_a + \\beta_2 x_1 + \\beta_3 x_1^2 + \\epsilon$$\n\n\n\n\n\n\n\n## RDD Nonlinearities   {.smaller background=\"#f2f1d5\"}\n\nWe can also add an interaction term (notice that I am changing the notation now to make it similar to MM)\n\n$$Y_i = \\alpha + \\beta_1 D_a + \\beta_2 (x - x_0) + \\beta_3 (x - x_0) D_a + \\epsilon$$\n\nThis allows for different inclinations before and after the cut.\n\n\n\n## RDD Nonlinearities   {.smaller background=\"#f2f1d5\"}\n\nOr even different nonlinearities before and after the cut:\n\n\n$$Y_i = \\alpha + \\beta_1 D_a + \\beta_2 (x - x_0) + \\beta_3 (x - x_0)^2 + \\beta_4 (x - x_0) D_a  + \\beta_5 (x - x_0)^2 D_a + \\epsilon$$\n\n\n![](figs/rdd6.png)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n# Example RDD  {.smaller background=\"#edecc0\"}\n\n## Example RDD **Clearly, this is not linear.** {.smaller background=\"#edecc0\"}\n\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\nlibrary(readxl)\nlibrary(ggplot2)\ndata  <- read_excel(\"files/RDD.xlsx\")\nggplot(data, aes(x, y))  + \n  geom_point(size=1.2) + \n  labs(y = \"\", x=\"\", title = \"Evolution of Y\") +\n  theme(plot.title = element_text(color=\"black\", size=20, face=\"bold\"),\n        panel.background = element_rect(fill = \"grey95\", colour = \"grey95\"),\n        axis.text.y = element_text(face=\"bold\", color=\"black\", size = 12),\n        axis.text.x = element_text(face=\"bold\", color=\"black\", size = 12),\n        legend.title = element_blank(),\n        legend.key.size = unit(1, \"cm\")) +\n    geom_smooth(method = \"lm\", fill = NA)\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n### Python\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"Python\" code-line-numbers=\"true\"}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n# Read Excel file\ndata = pd.read_excel(\"files/RDD.xlsx\")\n# Generate line graph - Including all observations together\nsns.set(style=\"whitegrid\")\nplt.figure(figsize=(10, 5))\nscatter_plot = sns.scatterplot(x='x', y='y', data=data, s=50)\nscatter_plot.set_title(\"Evolution of Y\", fontsize=20, fontweight='bold')\nscatter_plot.set_xlabel(\"\", fontsize=12, fontweight='bold')\nscatter_plot.set_ylabel(\"\", fontsize=12, fontweight='bold')\n# Add regression line\nsns.regplot(x='x', y='y', data=data, scatter=False, line_kws={'color': 'blue'})\nplt.show()\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n:::\n\n\n![](figs/graph1.svg)\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Example RDD  {.smaller background=\"#edecc0\"}\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\nlibrary(readxl)\nlibrary(ggplot2)\ndata  <- read_excel(\"files/RDD.xlsx\")\n# Creating  groups\ndata$treated <- 0\ndata$treated[data$x >= 101] <- 1  \n# Generate a line graph - two groups\nggplot(data, aes(x, y, group=treated, color = factor(treated)))  + \n    geom_point( size=1.25) + \n    labs(y = \"\", x=\"\", title = \"RDD exemplo\")+\n    theme(plot.title = element_text(color=\"black\", size=25, face=\"bold\"),\n          panel.background = element_rect(fill = \"grey95\", colour = \"grey95\"),\n          axis.text.y = element_text(face=\"bold\", color=\"black\", size = 16),\n          axis.text.x = element_text(face=\"bold\", color=\"black\", size = 16),\n          legend.title = element_blank(),\n          legend.key.size = unit(2, \"cm\")) +\n    geom_smooth(method = \"lm\", fill = NA)\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-22-3.png){fig-align='center' width=960}\n:::\n:::\n\n\n### Python\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"Python\" code-line-numbers=\"true\"}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n# Read Excel file\ndata = pd.read_excel(\"files/RDD.xlsx\")\n# Create treated variable\ndata['treated'] = 0\ndata.loc[data['x'] >= 101, 'treated'] = 1\n# Generate line graph with two groups\nsns.set(style=\"whitegrid\")\nplt.figure(figsize=(10, 5))\nscatter_plot = sns.scatterplot(x='x', y='y', hue='treated', style='treated', data=data, s=50)\nscatter_plot.set_title(\"RDD exemplo\", fontsize=25, fontweight='bold')\nscatter_plot.set_xlabel(\"\", fontsize=16, fontweight='bold')\nscatter_plot.set_ylabel(\"\", fontsize=16, fontweight='bold')\nscatter_plot.legend().set_title('')\nscatter_plot.legend(title='', loc='upper left', fontsize='small')\n# Add regression lines\nsns.regplot(x='x', y='y', data=data[data['treated'] == 0], scatter=False, line_kws={'color': 'blue'})\nsns.regplot(x='x', y='y', data=data[data['treated'] == 1], scatter=False, line_kws={'color': 'orange'})\nplt.show()\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-23-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n:::\n\n\n![](figs/graph2.svg) \n\n:::\n\n\n\n\n\n\n\n\n\n## Example RDD  {.smaller background=\"#edecc0\"}\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\nlibrary(readxl)\nlibrary(ggplot2)\ndata  <- read_excel(\"files/RDD.xlsx\")\n# Creating  groups\ndata$treated <- 0\ndata$treated[data$x >= 101] <- 1  \n# define cut\ncut <- 100\nband <- 50\nxlow = cut - band\nxhigh = cut + band\n# subset the data for the bandwidth\ndata <- subset(data, x > xlow & x <= xhigh, select=c(x, y,  treated))\n# Generate a line graph - two groups\nggplot(data, aes(x, y, group=treated, color = factor(treated)))  + \n  geom_point( size=1.25) + \n  labs(y = \"\", x=\"\", title = \"RDD example\")+\n  theme(plot.title = element_text(color=\"black\", size=25, face=\"bold\"),\n        panel.background = element_rect(fill = \"grey95\", colour = \"grey95\"),\n        axis.text.y = element_text(face=\"bold\", color=\"black\", size = 16),\n        axis.text.x = element_text(face=\"bold\", color=\"black\", size = 16),\n        legend.title = element_blank(),\n        legend.key.size = unit(2, \"cm\")) +\n  geom_smooth(method = \"lm\", fill = NA)\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-25-3.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n### Python\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"Python\" code-line-numbers=\"true\"}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n# Read Excel file\ndata = pd.read_excel(\"files/RDD.xlsx\")\n# Create treated variable\ndata['treated'] = 0\ndata.loc[data['x'] >= 101, 'treated'] = 1\n# Define cut, band, and subset data\ncut = 100\nband = 50\nxlow = cut - band\nxhigh = cut + band\ndata = data[(data['x'] > xlow) & (data['x'] <= xhigh)][['x', 'y', 'treated']]\n# Generate line graph with two groups\nsns.set(style=\"whitegrid\")\nplt.figure(figsize=(10, 5))\nscatter_plot = sns.scatterplot(x='x', y='y', hue='treated', style='treated', data=data, s=50)\nscatter_plot.set_title(\"RDD example\", fontsize=25, fontweight='bold')\nscatter_plot.set_xlabel(\"\", fontsize=16, fontweight='bold')\nscatter_plot.set_ylabel(\"\", fontsize=16, fontweight='bold')\nscatter_plot.legend().set_title('')\nscatter_plot.legend(title='', loc='upper left', fontsize='small')\n# Add regression lines\nsns.regplot(x='x', y='y', data=data[data['treated'] == 0], scatter=False, line_kws={'color': 'blue'})\nsns.regplot(x='x', y='y', data=data[data['treated'] == 1], scatter=False, line_kws={'color': 'orange'})\nplt.show()\n```\n\n::: {.cell-output-display}\n![](part_2_files/figure-revealjs/unnamed-chunk-26-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n:::\n\n\n![](figs/graph3.svg)\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Example RDD  {.smaller background=\"#edecc0\"}\n\n::: panel-tabset\n### R\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"R\" code-line-numbers=\"true\"}\nlibrary(readxl)\nlibrary(ggplot2)\ndata  <- read_excel(\"files/RDD.xlsx\")\ndata$treated <- 0\ndata$treated[data$x >= 101] <- 1  \ncut <- 100\nband <- 50\nxlow = cut - band\nxhigh = cut + band\ndata <- subset(data, x > xlow & x <= xhigh, select=c(x, y,  treated))\n# Generating xhat - Now we are going to the RDD\ndata$xhat <- data$x - cut\n# Generating xhat * treated to allow different inclinations (we will use the findings of the last graph, i.e. that each group has a different trend.)\ndata$xhat_treated <- data$xhat * data$treated\n# RDD Assuming different trends\nrdd <- lm(y  ~ xhat + treated  + xhat_treated, data = data)\nsummary(rdd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ xhat + treated + xhat_treated, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-12.9477  -3.2607   0.6875   3.2227  12.2004 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  55.83059    1.53681  36.329  < 2e-16 ***\nxhat          0.29431    0.05405   5.445 3.97e-07 ***\ntreated      28.93921    2.20672  13.114  < 2e-16 ***\nxhat_treated -0.51587    0.07644  -6.749 1.13e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.515 on 96 degrees of freedom\nMultiple R-squared:  0.8942,\tAdjusted R-squared:  0.8909 \nF-statistic: 270.3 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Python\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.python .cell-code  code-fold=\"true\" code-summary=\"Python\" code-line-numbers=\"true\"}\nimport pandas as pd\nimport statsmodels.api as sm\ndata = pd.read_excel(\"files/RDD.xlsx\")\n# Generate treated variable\ndata['treated'] = 0\ndata.loc[data['x'] >= 101, 'treated'] = 1\n# Define cut and band\ncut = 100\nband = 50\nxlow = cut - band\nxhigh = cut + band\n# Subset data\ndata = data[(data['x'] > xlow) & (data['x'] <= xhigh)]\n# Generate xhat and xhat_treated\ndata['xhat'] = data['x'] - cut\ndata['xhat_treated'] = data['xhat'] * data['treated']\n# Regression\nX = data[['xhat', 'treated', 'xhat_treated']]\nX = sm.add_constant(X)  # Add a constant term\ny = data['y']\nmodel = sm.OLS(y, X).fit()\nprint(model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                      y   R-squared:                       0.894\nModel:                            OLS   Adj. R-squared:                  0.891\nMethod:                 Least Squares   F-statistic:                     270.3\nDate:                ter, 30 jan 2024   Prob (F-statistic):           1.14e-46\nTime:                        15:36:45   Log-Likelihood:                -310.60\nNo. Observations:                 100   AIC:                             629.2\nDf Residuals:                      96   BIC:                             639.6\nDf Model:                           3                                         \nCovariance Type:            nonrobust                                         \n================================================================================\n                   coef    std err          t      P>|t|      [0.025      0.975]\n--------------------------------------------------------------------------------\nconst           55.8306      1.537     36.329      0.000      52.780      58.881\nxhat             0.2943      0.054      5.445      0.000       0.187       0.402\ntreated         28.9392      2.207     13.114      0.000      24.559      33.320\nxhat_treated    -0.5159      0.076     -6.749      0.000      -0.668      -0.364\n==============================================================================\nOmnibus:                        0.995   Durbin-Watson:                   2.114\nProb(Omnibus):                  0.608   Jarque-Bera (JB):                1.079\nSkew:                          -0.221   Prob(JB):                        0.583\nKurtosis:                       2.747   Cond. No.                         151.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n\n\n:::\n:::\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nimport excel \"files/RDD.xlsx\", firstrow clear\ngen treated = 0\nreplace treated = 1 if x >= 101\ngen cut = 100\ngen band = 50\ngen xlow = cut - band\ngen xhigh = cut + band\nkeep if x > xlow & x <= xhigh\ngen xhat = x - cut\ngen xhat_treated = xhat * treated\nregress y xhat treated xhat_treated\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(2 vars, 200 obs)\n\n\n(100 real changes made)\n\n\n\n\n\n(100 observations deleted)\n\n      Source |       SS           df       MS      Number of obs   =       100\n-------------+----------------------------------   F(3, 96)        =    270.35\n       Model |  24669.3025         3  8223.10084   Prob > F        =    0.0000\n    Residual |  2920.00749        96  30.4167447   R-squared       =    0.8942\n-------------+----------------------------------   Adj R-squared   =    0.8909\n       Total |    27589.31        99  278.679899   Root MSE        =    5.5151\n\n------------------------------------------------------------------------------\n           y | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        xhat |   .2943097   .0540479     5.45   0.000     .1870255     .401594\n     treated |   28.93921   2.206717    13.11   0.000     24.55891    33.31951\nxhat_treated |  -.5158703   .0764353    -6.75   0.000    -.6675932   -.3641475\n       _cons |   55.83059   1.536805    36.33   0.000     52.78005    58.88112\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n## Example RDD  {.smaller background=\"#edecc0\"}\n\nThe coefficient of x before the cut is 0.29 (t-stat 5.45), and after the cut, it is -0.51 (t-stat -6.75). \n\nWe also have the coefficient of the treatment, which is measured by the \"jump\" that occurs near the cut: **an estimated coefficient of 28.9 (t-stat 13.11). **\n\nIf this were a real example, this would be the causal effect of receiving the treatment (i.e., being beyond the cut).\n\n\n\n\n\n\n\n\n\n\n# Final comments RDD {.smaller background=\"#f0eeb4\"}\n\n## Final comments RDD {.smaller background=\"#f0eeb4\"}\n\n\n**Sensitivity to specification**\n\nMisspecification can lead to a \"spurious jump\". **Do not mix nonlinearity with a discontinuity**.\n\n. . . \n\n**Sensitivity to window**\n\nAlso, need to check many alternative $h$. \n\n. . . \n\n**Smoothness of the running around the cut**\n\nThe distribution of X should be smooth around the cut. If it is not, it might indicate that the treatment assignment was not random. \n\n. . . \n\n**Test comparability of units around the cut**\n\nCovariates balance. You can check whether there are jumps in control variables as an additional robustness.\n\n. . . \n\n**Placebo tests**\n\nTest whether the treatment is zero when it should be zero.\n\n\n\n\n\n\n\n\n\n\n# Synthetic Control {.smaller background=\"#f2c7c4\"}\n\n## Synthetic Control {.smaller background=\"#f2c7c4\"}\n\nIt is a method to estimate the effect of events or policy interventions, often at an **aggregate level** (cities, states, etc.)\n\nThe event occurs often in **only one unit**.\n\nIt compares the evolution of the  outcome for the treated unit to the evolution of the control group.\n\n- The control group contains many units. \n\n. . . \n\nThe limitation is often the selection of the control group. It is very **ambiguous**.\n\n\n\n\n\n\n## Synthetic Control {.smaller background=\"#f2c7c4\"}\n\n[Abadie, Diamond, and Hainmueller (2010)](https://doi.org/10.1198/jasa.2009.ap08746) apply synth  by using a cigarette tax in California called Proposition 99.\n\n*In 1988, California passed comprehensive tobacco control legislation called Proposition 99.*\n\n*Proposition 99 increased cigarette taxes by $0.25 a pack, spurred clean-air ordinances throughout the state, funded anti-smoking media campaigns, earmarked tax revenues to health and anti-smoking budgets, and produced more than $100 million a year in anti-tobacco projects.*\n\n*Other states had similar control programs, and they were dropped from their analysis.* [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#cuba-miami-and-the-mariel-boatlift)\n\n\n\n\n\n\n## Synthetic Control {.smaller background=\"#f2c7c4\"}\n\nThere was a trend before the treatment. **How can we estimate the causal effect?**\n\n![](figs/synth1.png)\n\n\n\n\n\n\n\n## Synthetic Control {.smaller background=\"#f2c7c4\"}\n\nThe goal is to  elect an optimal set of weights that when applied to the rest of the country produces the following figure: \n\n![](figs/synth3.png)\n\n\n## Synthetic Control {.smaller background=\"#f2c7c4\"}\n\nThe variables used for computing the weights are the following. You are creating weights such that weighting the other states, you can create a synthetic California. **Notice that, so far, the product of this analysis is only two data points per period.** \n\n\n![](figs/synth2.png)\n\n\n\n## Synthetic Control {.smaller background=\"#f2c7c4\"}\n\n**Tip**: Synth is also an graphical method, so graphs like the following are common. This is the difference between the two series.\n\n![](figs/synth4.png)\n\n\n\n\n# Inference {.smaller background=\"#d49692\"}\n\n## Inference {.smaller background=\"#d49692\"}\n\n\n**Notice that, so far, the product of this analysis is only two data points per period.** How can you stablish a \"significant\" causal effect?\n\n\n**Steps**\n\n1) Apply synth to each state in the control group (also called \"donor pool\"). \n\n2) Obtain a distribution of placebos.\n\n3) Compare the gap for California to the distribution of the placebo gaps.\n\n4) Then, test whether the effect for the treated unit is large enough relative to the placebos (i.e., to the effect estimated for a placebo unit randomly selected).\n\n\n\n\n\n\n\n## Inference {.smaller background=\"#d49692\"}\n\nNotice the bold line (treated unit) after the treatment. It is at the bottom. \n\n![](figs/synth5.png)\n\n## Inference {.smaller background=\"#d49692\"}\n\n*Abadie, Diamond, and Hainmueller (2010) recommend iteratively dropping the states whose pre-treatment RMSPE is considerably different than California’s because as you can see, they’re kind of blowing up the scale and making it hard to see what’s going on.* [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#cuba-miami-and-the-mariel-boatlift)\n\n![](figs/synth6.png)\n\n\n\n\n\n\n## Inference {.smaller background=\"#d49692\"}\n\nThe previous figure suggests the effect is large enough relative to the placebo effects.\n\n. . . \n\n\n1) The root mean squared prediction error (RMSPE) is:\n\n$$RMSPE = \\bigg (\\dfrac{1}{T-T_0} \\sum_{t=T_0+t}^T \\bigg (Y_{1t} - \\sum_{j=2}^{J+1} w_j^* Y_{jt} \\bigg )^2 \\bigg )^{\\tfrac{1}{2}}$$\n\n*It shows how far predictions fall from measured true values using Euclidean distance.*\n\n\n\n2) Sort the ratio post- to pre-treatment RMSPE in descending order\n\n3) Calculate the p-value as $\\frac{Rank}{Total}$.\n\n\n. . . \n\nBasically, these steps give how likely is the occurrence of the treated unit distance vis-a-vis the average placebo.\n\n\n\n\n\n\n\n\n\n\n\n## Inference {.smaller background=\"#d49692\"}\n\n**RMSPE**: in the previous example, California has the largest increase in the error after the treatment. Position 1 out of 39 states, implying an exact p-value of $\\frac{1}{38}=0.026$ (significant). \n\n\n\n![](figs/synth7.png)\n\n\n\n\n\n\n\n\n\n\n\n\n# Example Synth  {.smaller background=\"#f5a7a2\"}\n\n## Example Synth  {.smaller background=\"#f5a7a2\"}\n\n::: panel-tabset\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/synth_smoking.dta , clear\ntsset state year\nsynth cigsale beer(1984(1)1988) lnincome retprice age15to24 cigsale(1988) cigsale(1980) cigsale(1975), trunit(3) trperiod(1989) \n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Tobacco Sales in 39 US States)\n\n\nPanel variable: state (strongly balanced)\n Time variable: year, 1970 to 2000\n         Delta: 1 unit\n\n-------------------------------------------------------------------------------\nSynthetic Control Method for Comparative Case Studies\n-------------------------------------------------------------------------------\n\nFirst Step: Data Setup\n-------------------------------------------------------------------------------\ncontrol units: for 38 of out 38 units missing obs for predictor lnincome in per\n> iod 1970 -ignored for averaging\ncontrol units: for 38 of out 38 units missing obs for predictor lnincome in per\n> iod 1971 -ignored for averaging\ntreated unit: for 1 of out 1 units missing obs for predictor lnincome in period\n>  1970 -ignored for averaging\ntreated unit: for 1 of out 1 units missing obs for predictor lnincome in period\n>  1971 -ignored for averaging\n-------------------------------------------------------------------------------\nData Setup successful\n-------------------------------------------------------------------------------\n                Treated Unit: California\n               Control Units: Alabama, Arkansas, Colorado, Connecticut,\n                              Delaware, Georgia, Idaho, Illinois, Indiana,\n                              Iowa, Kansas, Kentucky, Louisiana, Maine,\n                              Minnesota, Mississippi, Missouri, Montana,\n                              Nebraska, Nevada, New Hampshire, New Mexico,\n                              North Carolina, North Dakota, Ohio, Oklahoma,\n                              Pennsylvania, Rhode Island, South Carolina, South\n                              Dakota, Tennessee, Texas, Utah, Vermont,\n                              Virginia, West Virginia, Wisconsin, Wyoming\n-------------------------------------------------------------------------------\n          Dependent Variable: cigsale\n  MSPE minimized for periods: 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979\n                              1980 1981 1982 1983 1984 1985 1986 1987 1988\nResults obtained for periods: 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979\n                              1980 1981 1982 1983 1984 1985 1986 1987 1988 1989\n                              1990 1991 1992 1993 1994 1995 1996 1997 1998 1999\n                              2000\n-------------------------------------------------------------------------------\n                  Predictors: beer(1984(1)1988) lnincome retprice age15to24\n                              cigsale(1988) cigsale(1980) cigsale(1975)\n-------------------------------------------------------------------------------\nUnless period is specified\npredictors are averaged over: 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979\n                              1980 1981 1982 1983 1984 1985 1986 1987 1988\n-------------------------------------------------------------------------------\n\nSecond Step: Run Optimization\n-------------------------------------------------------------------------------\n-------------------------------------------------------------------------------\nOptimization done\n-------------------------------------------------------------------------------\n\nThird Step: Obtain Results\n-------------------------------------------------------------------------------\nLoss: Root Mean Squared Prediction Error\n\n---------------------\n   RMSPE |  1.943233 \n---------------------\n-------------------------------------------------------------------------------\nUnit Weights:\n\n----------------------------\n         Co_No | Unit_Weight\n---------------+------------\n       Alabama |           0\n      Arkansas |           0\n      Colorado |        .285\n   Connecticut |        .101\n      Delaware |           0\n       Georgia |           0\n         Idaho |           0\n      Illinois |           0\n       Indiana |           0\n          Iowa |           0\n        Kansas |           0\n      Kentucky |           0\n     Louisiana |           0\n         Maine |           0\n     Minnesota |           0\n   Mississippi |           0\n      Missouri |           0\n       Montana |           0\n      Nebraska |           0\n        Nevada |        .245\n New Hampshire |           0\n    New Mexico |           0\nNorth Carolina |           0\n  North Dakota |           0\n          Ohio |           0\n      Oklahoma |           0\n  Pennsylvania |           0\n  Rhode Island |           0\nSouth Carolina |           0\n  South Dakota |           0\n     Tennessee |           0\n         Texas |           0\n          Utah |        .369\n       Vermont |           0\n      Virginia |           0\n West Virginia |           0\n     Wisconsin |           0\n       Wyoming |           0\n----------------------------\n-------------------------------------------------------------------------------\nPredictor Balance:\n\n------------------------------------------------------\n                               |   Treated  Synthetic \n-------------------------------+----------------------\n             beer(1984(1)1988) |     24.28   23.22596 \n                      lnincome |  10.03176   9.867266 \n                      retprice |  66.63684   65.40743 \n                     age15to24 |  .1786624   .1825559 \n                 cigsale(1988) |      90.1    92.6063 \n                 cigsale(1980) |     120.2   120.3907 \n                 cigsale(1975) |     127.1   126.7094 \n------------------------------------------------------\n-------------------------------------------------------------------------------\n\ncounter | pri_inf  | dual_inf  | pri_obj   | dual_obj  | sigfig | alpha  | nu \n----------------------------------------------------------------------------------\n      0 | 8.29e+001 | 7.80e-006 | -1.26e+001 | -3.93e+002 |  0.000 | 0.0000 | 1.00e+002\n      1 | 5.04e-001 | 4.74e-008 | -1.26e+001 | -7.02e+002 |  0.000 | 0.9939 | 3.05e-005\n      2 | 2.85e-003 | 2.68e-010 | -1.25e+001 | -2.80e+001 |  0.000 | 0.9943 | 2.70e-006\n      3 | 1.60e-004 | 1.51e-011 | -1.26e+001 | -1.34e+001 |  1.193 | 0.9438 | 5.40e-006\n      4 | 1.57e-005 | 1.47e-012 | -1.26e+001 | -1.27e+001 |  2.000 | 0.9022 | 9.21e-007\n      5 | 9.72e-006 | 9.13e-013 | -1.26e+001 | -1.27e+001 |  2.207 | 0.3806 | 6.37e-006\n      6 | 2.91e-006 | 2.73e-013 | -1.26e+001 | -1.26e+001 |  2.714 | 0.7006 | 8.69e-007\n      7 | 5.05e-007 | 4.75e-014 | -1.26e+001 | -1.26e+001 |  3.414 | 0.8263 | 8.90e-008\n      8 | 1.70e-007 | 1.60e-014 | -1.26e+001 | -1.26e+001 |  3.881 | 0.6640 | 6.85e-008\n      9 | 2.24e-008 | 2.10e-015 | -1.26e+001 | -1.26e+001 |  4.685 | 0.8682 | 3.46e-009\n     10 | 2.57e-010 | 2.43e-017 | -1.26e+001 | -1.26e+001 |  6.512 | 0.9885 | 4.02e-012\n     11 | 1.28e-012 | 1.87e-018 | -1.26e+001 | -1.26e+001 |  8.807 | 0.9950 | 1.14e-014\n     12 | 6.45e-015 | 1.86e-018 | -1.26e+001 | -1.26e+001 | 11.104 | 0.9950 | 5.78e-017\n     13 | 8.88e-016 | 2.02e-018 | -1.26e+001 | -1.26e+001 | 13.407 | 0.9950 | 2.91e-019\n----------------------------------------------------------------------------------\noptimization converged\n```\n\n\n:::\n:::\n\n\n:::\n\n\n## Example Synth  {.smaller background=\"#f5a7a2\"}\n\n::: panel-tabset\n\n\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/synth_smoking.dta , clear\nsynth cigsale beer lnincome(1980&1985) retprice cigsale(1988) cigsale(1980) cigsale(1975), trunit(3) trperiod(1989) fig\nquietly graph export figs/synth1.svg, replace\n```\n:::\n\n\n![](figs/synth1.svg)\n\n:::\n\n\n\n\n\n\n\n\n\n## Example Synth  {.smaller background=\"#f5a7a2\"}\n\n\n*Authors using synthetic control must do more than merely run the synth command when doing comparative case studies.* \n\n*They must find the exact-values through placebo-based inference, check for the quality of the pre-treatment fit, investigate the balance of the covariates used for matching, and check for the validity of the model through placebo estimation (e.g., rolling back the treatment date).*\n\n\n\n\n\n\n\n\n\n\n\n\n\n# [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#prison-construction-and-black-male-incarceration)  {.smaller background=\"#de938e\"}\n\n\n## [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#prison-construction-and-black-male-incarceration)  {.smaller background=\"#de938e\"}\n\nIn 1992, Texas expanded the prision system operational capacity.\n\n![](figs/synth8.png)\n\n\n\n\n\n\n\n## [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#prison-construction-and-black-male-incarceration)  {.smaller background=\"#de938e\"}\n\nThis is what happened.\n\n![](figs/synth9.png)\n\n\n\n\n\n\n## [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#prison-construction-and-black-male-incarceration)  {.smaller background=\"#de938e\"}\n\nSynthetic Texas.\n\n![](figs/synth10.png)\n\n\n\n\n## [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#prison-construction-and-black-male-incarceration)  {.smaller background=\"#de938e\"}\n\nGap between Synthetic Texas and Texas.\n\n![](figs/synth11.png)\n\n\n\n\n## [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#prison-construction-and-black-male-incarceration)  {.smaller background=\"#de938e\"}\n\nBuilding Placebos.\n\n![](figs/synth13.png)\n\n\n\n\n## [Mastering Metrics](https://mixtape.scunning.com/10-synthetic_control#prison-construction-and-black-male-incarceration)  {.smaller background=\"#de938e\"}\n\nTexas is the one in the far right tail. \n\n![](figs/synth12.png)\n\n\n\n\n\n\n\n# Introduction IV {.smaller background=\"#bcd3f7\"}\n\n## Introduction IV {.smaller background=\"#bcd3f7\"}\n\nImagine the following model\n\n$$Ln(wage)=\\alpha + \\beta_1 educ + \\epsilon$$\n\nWe can infer that *educ* is correlated with *ability*, but the latter is in the error term. \n\n*educ* in this case is \"endogenous\".\n\n$$Cov(educ, \\epsilon) \\neq 0$$\n\n\n\n## Introduction IV {.smaller background=\"#bcd3f7\"}\n\n**The setup of an IV is**\n\nSuppose that we have an observable variable z that satisfies these two assumptions: \n\n(1) z is uncorrelated with u:\n\n$$Cov(z, \\epsilon) = 0$$\n\n\n(2) z is correlated with x:\n\n$$Cov(z, x) \\neq 0$$\n\n\n\nThen, we call z an instrumental variable for x, or sometimes simply an instrument for x.\n\n\n\n\n\n## Introduction IV {.smaller background=\"#bcd3f7\"}\n\nBefore we continue,\n\nIV is not a model, it is an **estimation method** \n\nI'll call it a **Design**.\n\n\nDo not say, I estimated an IV model (more often than it should be).\n\n\n\n\n\n\n\n\n\n\n# Instrumental Variables {.smaller background=\"#8eadde\"}\n\n## Instrumental Variables {.smaller background=\"#8eadde\"}\n\nImagine that you have one independent variable that is \"endogenous\":\n\n- $Cov(x_k,\\mu)\\neq 0$\n\n- You may have many other independent variables not \"endogenous\"\n\n. . .\n\nIn this situation:\n\n- $B_k$ is biased\n\n- The other betas will likely be biased as well, since it is unlikely that all other Xs are not correlated with $x_k$\n\n\n\n\n\n\n\n\n## Instrumental Variables {.smaller background=\"#8eadde\"}\n\n$x_k$ is the endogenous variable.\n\n- It has \"good\" variation: \n\n  - the part that varies that is not correlated with $\\mu$\n\n- It has \"bad\" variation: \n\n  - the part that varies that is  correlated with $\\mu$\n\n. . . \n\nLet's assume now that you can find an instrument $z$\n\n- The instrument $z$ is correlated with $X_k$, but only the \"good\" variation, not the \"bad\".\n\n- The instrument $z$ does not explain $y$ directly, only through $x_k$.\n\n  - **Only through** condition.\n\n\n\n\n\n\n\n\n\n\n## Instrumental Variables {.smaller background=\"#8eadde\"}\n\n**Relevance Condition**\n\nThe instrument $z$ is correlated with $x_k$.\n\n- This assumption is easy to test. Simply run a regression of $x=f(z, all\\; Xs)$ and check the significance of the $\\beta_z$.\n\n- This is called the **first stage of an IV regression**\n\n  - **Tip**: Always show the beta coefficient and the R2 (even if low) of the first-stage.  \n\n. . . \n\n**Exclusion Condition**\n\nThe instrument $z$ is not correlated with $\\mu$.\n\n- That is $cov(z,\\mu) = 0$\n\n- As all correlations with $\\mu$, you cannot test this prediction. You have to rely on the theory, create a story about that.\n\n\n\n\n\n\n\n\n## Instrumental Variables {.smaller background=\"#8eadde\"}\n\n**An example of IV** [Murray](https://doi.org/10.1257/jep.20.4.111).\n\n![](figs/iv2.png)\n\n\n\n\n\n\n\n\n\n\n\n## Instrumental Variables {.smaller background=\"#8eadde\"}\n\n**An example of IV** [Murray](http://dx.doi.org/10.1016/j.jcorpfin.2013.12.013).\n\n![](figs/iv6.png)\n\n\n\n\n\n\n## Instrumental Variables {.smaller background=\"#8eadde\"}\n\n[Mixtape](https://mixtape.scunning.com/07-instrumental_variables#good-instruments-should-feel-weird)\n\n**Good instruments should feel weird**\n\nParents with two same-gender kids are more likely to try a third kid than a diverse-gender pair of parents.\n\nSo, you may use the gender of the kids as instrument for the likelihood of the mother go back to the labor market.\n\n\n\n\n\n\n# Angrist's example {.smaller background=\"#d2e2fc\"}\n\n## Angrist's example {.smaller background=\"#d2e2fc\"}\n\nRemember the **Fuzzy RDD**.\n\n- There is the *treatment*\n- There is the *position* (before or after the cut) \n\nThe *position* is an indication of receiving or not the treatment, but it is not definitive.\n\nThus, we can use the *position* as an IV for the treatment.\n\n\n\n## Angrist's example {.smaller background=\"#d2e2fc\"}\n\n[Mixtape](https://mixtape.scunning.com/07-instrumental_variables#the-problem-of-weak-instruments)\n\n*One of the more seminal papers in instrumental variables for the modern period is Angrist and Krueger (1991).* \n\n*Their idea is simple and clever; a quirk in the United States educational system is that a child enters a grade on the basis of his or her birthday.* \n\n*For a long time, that cutoff was late December. If children were born on or before December 31, then they were assigned to the first grade. But if their birthday was on or after January 1, they were assigned to kindergarten. *\n\n*Thus two people—one born on December 31 and one born on January 1—were exogenously assigned different grades.*\n\nEveryone is forced to leave school when 16.\n\n\n\n\n## Angrist's example {.smaller background=\"#d2e2fc\"}\n\n[Mixtape](https://mixtape.scunning.com/07-instrumental_variables#the-problem-of-weak-instruments)\n\n![](figs/iv3.png)\n\n*Angrist and Krueger had the insight that that small quirk was exogenously assigning more schooling to people born later in the year.*\n\n*The person born in December would reach age 16 with more education than the person born in January*\n\n\n\n\n## Angrist's example {.smaller background=\"#d2e2fc\"}\n\n[Mixtape](https://mixtape.scunning.com/07-instrumental_variables#the-problem-of-weak-instruments)\n\n![](figs/iv4.jpg)\n\n\n**What is the instrument here?**\n\n\n\n## Angrist's example {.smaller background=\"#d2e2fc\"}\n\n[Mixtape](https://mixtape.scunning.com/07-instrumental_variables#the-problem-of-weak-instruments)\n\n\n**What is the instrument here?**\n\nThe instrument is the quarter of birth.\n\n- People born in the 3rd and 4th quarter receive more education than others due to **compulsory schooling**.\n\n\n\n\n\n\n\n\n# Two-stage least squares (2SLS) {.smaller background=\"#abc8f5\"}\n\n## Two-stage least squares  (2SLS){.smaller background=\"#abc8f5\"}\n\n\nOne of the more intuitive instrumental variables estimators is the 2SLS. \n\n\n\n**The first stage is**\n\n$$x_k = \\delta + \\delta_1 z + \\delta_2 x_1 + . . .+ \\delta_n x_n + \\mu$$\n\nThen, you predict $x_k$ using the first stage.\n\n- \"predict\" means that you are finding the \"response\" Y of the equation after estimating the coefficients\n\n $$\\hat{x_k} = \\hat{\\delta} + \\hat{\\delta_1} z + \\hat{\\delta_2} x_1 + . . . + \\hat{\\delta_n} x_n $$\n\n\n. . . \n\nThen, **the second stage** is:\n\n\n$$y = \\alpha + \\beta_1 \\hat{x_k} + \\beta_2 x_1 + . . .+  \\beta_n x_n + \\mu$$\n\n\nThe idea using $\\hat{x_k}$ is that it represents only the variation that is not correlated with $\\mu$.\n\n\n\n\n\n\n\n\n## Instrumental Variables {.smaller background=\"#abc8f5\"}\n\nWe can write that:\n\n$$\\beta_1= \\frac{Cov(z,y)}{Cov(z,x_k)}$$\n\n\n- It shows that $\\beta_1$ is the population covariance between z and y divided by the population covariance between z and x.\n\n- Notice how this fails if z and x are uncorrelated, that is, if $Cov(z, x) = 0$ \n\n\n\n\n. . . \n\n\n\n$$\\beta_1= \\frac{\\sum_{i=1}^n(z_i-\\bar{z})(y_i-\\bar{y})}{\\sum_{i=1}^n(z_i-\\bar{z})(x_i-\\bar{x})}$$\n\n\nNotice that if $z$ and $x$ are the same (i.e., perfect correlation), $\\beta_1$ above is the OLS $\\beta$\n\n\n$$\\beta_1= \\frac{\\sum_{i=1}^n(x_i-\\bar{x})(y_i-\\bar{y})}{\\sum_{i=1}^n(x_i-\\bar{x})^2}$$\n\n\n\n# Weak Instruments  {.smaller background=\"#8da6cc\"}\n\n## Weak Instruments {.smaller background=\"#8da6cc\"}\n\nI did not demonstrate here, but we can say that (see pp; 517-18 Wooldridge):\n\n- though IV is consistent when $z$ and $u$ are uncorrelated and $z$ and $x$ have any positive or negative correlation, IV estimates can have large standard errors, especially if $z$ and $x$ are only weakly correlated.\n\nThis gives rise to the week instruments problem.\n\nWe can write the probability limit of the IV estimator:\n\n$$plim \\hat{\\beta_{iv}} = \\beta_1 + \\frac{Corr(z,\\mu)}{Corr(z,x)} \\times \\frac{\\sigma_{\\mu}}{\\sigma_x}$$\n\nIt shows that, even if $Corr(z,\\mu)$ is small, the inconsistency in the IV estimator can be very large if $Corr(z,x)$ is also small.\n\n\n\n\n\n\n\n## Weak Instruments {.smaller background=\"#8da6cc\"}\n\nTwo tips:\n\n1) Look at the F-stat of the first-stage. It should not be low.\n\n2) The sign of the coefficient in the first stage should be as expected.\n\n3) Look at the S.E. When the instrument is week, the S.E., are even larger than it should be.\n\n. . .\n\nOne more tip,\n\n4) Avoid computing the first stage by hand, it would give wrong estimates of the S.E. in the second stage.\n\n\n\n\n\n\n\n\n\n\n\n# Example {.smaller background=\"#95a9c7\"}\n\n## Example  {.smaller background=\"#95a9c7\"}\n\nOLS\n\n::: panel-tabset\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/mroz.dta , clear\nreg lwage educ \n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Source |       SS           df       MS      Number of obs   =       428\n-------------+----------------------------------   F(1, 426)       =     56.93\n       Model |  26.3264237         1  26.3264237   Prob > F        =    0.0000\n    Residual |  197.001028       426  .462443727   R-squared       =    0.1179\n-------------+----------------------------------   Adj R-squared   =    0.1158\n       Total |  223.327451       427  .523015108   Root MSE        =    .68003\n\n------------------------------------------------------------------------------\n       lwage | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        educ |   .1086487   .0143998     7.55   0.000     .0803451    .1369523\n       _cons |  -.1851969   .1852259    -1.00   0.318    -.5492674    .1788735\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n\n\n\n\n## Example  {.smaller background=\"#95a9c7\"}\n\nThe IV estimate of the return to education is 5.9%, which is barely more than one-half of the  OLS estimate. This suggests that the OLS estimate is too high and is consistent with omitted ability bias.\n\n::: panel-tabset\n\n### Stata\n\n\n::: {.cell layout-align=\"center\" output-location='default'}\n\n```{.stata .cell-code  code-fold=\"true\" code-summary=\"Stata\" code-line-numbers=\"true\"}\nuse files/mroz.dta , clear\nivreg lwage (educ =fatheduc ) , first\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFirst-stage regressions\n-----------------------\n\n      Source |       SS           df       MS      Number of obs   =       428\n-------------+----------------------------------   F(1, 426)       =     88.84\n       Model |  384.841983         1  384.841983   Prob > F        =    0.0000\n    Residual |  1845.35428       426  4.33181756   R-squared       =    0.1726\n-------------+----------------------------------   Adj R-squared   =    0.1706\n       Total |  2230.19626       427  5.22294206   Root MSE        =    2.0813\n\n------------------------------------------------------------------------------\n        educ | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n    fatheduc |   .2694416   .0285863     9.43   0.000     .2132538    .3256295\n       _cons |   10.23705   .2759363    37.10   0.000     9.694685    10.77942\n------------------------------------------------------------------------------\n\n\nInstrumental variables 2SLS regression\n\n      Source |       SS           df       MS      Number of obs   =       428\n-------------+----------------------------------   F(1, 426)       =      2.84\n       Model |  20.8673618         1  20.8673618   Prob > F        =    0.0929\n    Residual |  202.460089       426  .475258426   R-squared       =    0.0934\n-------------+----------------------------------   Adj R-squared   =    0.0913\n       Total |  223.327451       427  .523015108   Root MSE        =    .68939\n\n------------------------------------------------------------------------------\n       lwage | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n        educ |   .0591735   .0351418     1.68   0.093    -.0098994    .1282463\n       _cons |   .4411035   .4461018     0.99   0.323    -.4357311    1.317938\n------------------------------------------------------------------------------\nInstrumented: educ\n Instruments: fatheduc\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n# Final Comments {.smaller background=\"#bcd3f7\"}\n\n## Final Comments {.smaller background=\"#bcd3f7\"}\n\nWhen you have only one Z, you can say that the model is **just identified**.\n\nBut you can have multiple IVs, in which case you will say that the model is **overidentified**.\n\n- You can implement IV design just as before\n\n- The relevance and exclusion assumptions are there as well.\n\n. . . \n\nAssuming that both conditions are satisfied, you will have more asymptotic efficiency in the IV estimates.\n\n\n\n\n\n\n## Final Comments {.smaller background=\"#bcd3f7\"}\n\n**It is rare to have multiple Zs. You should be happy if you have a good one!**\n\n. . . \n\n\nBut if you do have multiple IVs, you can test their quality...\n\n- If they are all valid, you should get consistent estimates...\n\n- ... even if you use only a subset of them.\n\n- So the test is about how similar the estimates are if you use subsets of IVs.\n\n\n**But this test does not give really an answer about whether the IVs are good.**\n\nThis always come from theory.\n\n\n\n\n## Final Comments {.smaller background=\"#bcd3f7\"}\n\n**Some more comments:**\n\n1) If you have an interaction term between $x_1$ and $x_2$, and $z$ is the instrument for $x_1$, you can \"create\" the instrument $zx_2$ for $x_2$.\n\n. . . \n\n2) GMM uses lagged variables as instruments. But, this is not a good decision if the variables are highly serially correlated.\n\n  - Lagged total assets is not a good instrument for total assets.\n  \n. . . \n\n3) Using the average-group of variable X is also problematic (i.e., the industry average own. concentration as IV of firm-level own. concentration)\n\n - This is no different than a group FE, making hard to believe in the exclusion restriction.\n\n\n\n\n## THANK YOU!\n\n::: columns\n::: {.column width=\"30%\"}\n![](figs/fgv.png){fig-align=\"right\"}\n:::\n\n::: {.column width=\"70%\"}\n**Henrique Castro Martins**\n\n-   [henrique.martins\\@fgv.br](henrique.martins@fgv.br)\n-   <https://eaesp.fgv.br/en/people/henrique-castro-martins>\n-   [henriquemartins.net](https://henriquemartins.net/)\n-   <https://www.linkedin.com/in/henriquecastror/>\n:::\n:::\n",
    "supporting": [
      "part_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}