---
title: 'Estratégia Financeira/Financial Strategy'
subtitle: ' **Part 8 - Ch 15 Debt and Taxes** '
author:
  - name: ' **Henrique C. Martins (henrique.martins@fgv.br)** '
    affiliation: '**[FGV/EAESP](https://eaesp.fgv.br/en) **'
  - name: ' **Rafael B. Palazzi (rafaelpalazzi@gmail.com)** '
    affiliation: '**[FGV/EAESP](https://eaesp.fgv.br/en) **'
date-modified: last-modified
title-block-banner: true
format:
  html:
    css: webex.css
    include-after-body: webex.js
---




```{r, setup}
#| eval: true
#| results: asis
#| echo: false
#| warning: false

library(webexercises)

```


**In-class problems about *chapter 15 Debt and Taxes* by [Berk and Demarzo](https://www.amazon.com.br/Corporate-Finance-Global-Jonathan-Berk/dp/1292304154). **


**Solve these problems in class or soon after.**



::: {.callout-important}
**Type your answers with "." instead of ","!**
:::


## True or False
```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** Unlevered beta measures the risk of a company's stock against that of the broader market, including the impact of a company's capital structure and leverage, while levered beta measures the market risk of a company without the impact of debt."
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** The interest tax shield with permanent debt implies that a company with a permanent level of debt will receive a consistent tax benefit due to the deductibility of interest expenses."
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** The Market Value Balance Sheet provides information based on historical costs of a firm's assets and liabilities. "
q1_choices <- c( "True", answer="False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** The effective tax advantage of debt can be calculated by multiplying the firm's interest expense by the corporate tax rate. "
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** Holding stocks over bonds can provide a tax advantage due to the deferral of capital gains taxes until the asset is sold, which effectively lowers the capital gains tax rate."
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** The Optimal Capital Structure with Taxes refers to the best mix of debt and equity financing that maximizes a company's market value while minimizing its cost of capital, taking into account the tax benefits of debt financing. "
q1_choices <- c( answer="True", "False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** The Optimal Capital Structure with Taxes refers to the best mix of debt and equity financing that fully exploits the tax advantages of debt. "
q1_choices <- c( "True", answer="False")
cat(q1,longmcq(q1_choices))
```

```{r}
#| eval: true
#| results: asis
#| echo: false
#| warning: false
q1 <- " **Q:** A firm can reduce its overall WACC by increasing the amount of debt financing, and it should take on as much debt as possible as long as the debt is not risky."
q1_choices <- c( "True", answer="False")
cat(q1,longmcq(q1_choices))
```




::: {.callout-warning}
**Type your answers with "." instead of ","!**
:::
